/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteResourceRequest = {
  /**
   * The sourcedId of the resource to delete
   */
  sourcedId: string;
};

/** @internal */
export const DeleteResourceRequest$inboundSchema: z.ZodType<
  DeleteResourceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type DeleteResourceRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const DeleteResourceRequest$outboundSchema: z.ZodType<
  DeleteResourceRequest$Outbound,
  z.ZodTypeDef,
  DeleteResourceRequest
> = z.object({
  sourcedId: z.string(),
});

export function deleteResourceRequestToJSON(
  deleteResourceRequest: DeleteResourceRequest,
): string {
  return JSON.stringify(
    DeleteResourceRequest$outboundSchema.parse(deleteResourceRequest),
  );
}
export function deleteResourceRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResourceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResourceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResourceRequest' from JSON`,
  );
}
