/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteResultRequest = {
  /**
   * The sourcedId of the result to delete
   */
  sourcedId: string;
};

/** @internal */
export const DeleteResultRequest$inboundSchema: z.ZodType<
  DeleteResultRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type DeleteResultRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const DeleteResultRequest$outboundSchema: z.ZodType<
  DeleteResultRequest$Outbound,
  z.ZodTypeDef,
  DeleteResultRequest
> = z.object({
  sourcedId: z.string(),
});

export function deleteResultRequestToJSON(
  deleteResultRequest: DeleteResultRequest,
): string {
  return JSON.stringify(
    DeleteResultRequest$outboundSchema.parse(deleteResultRequest),
  );
}
export function deleteResultRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResultRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResultRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResultRequest' from JSON`,
  );
}
