/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteGradingPeriodRequest = {
  /**
   * The sourcedId of the grading period to delete
   */
  sourcedId: string;
};

/** @internal */
export const DeleteGradingPeriodRequest$inboundSchema: z.ZodType<
  DeleteGradingPeriodRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type DeleteGradingPeriodRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const DeleteGradingPeriodRequest$outboundSchema: z.ZodType<
  DeleteGradingPeriodRequest$Outbound,
  z.ZodTypeDef,
  DeleteGradingPeriodRequest
> = z.object({
  sourcedId: z.string(),
});

export function deleteGradingPeriodRequestToJSON(
  deleteGradingPeriodRequest: DeleteGradingPeriodRequest,
): string {
  return JSON.stringify(
    DeleteGradingPeriodRequest$outboundSchema.parse(deleteGradingPeriodRequest),
  );
}
export function deleteGradingPeriodRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGradingPeriodRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGradingPeriodRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGradingPeriodRequest' from JSON`,
  );
}
