/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExportResourceToCommonCartridgeRequest = {
  /**
   * The sourcedId of the resource to export
   */
  sourceId: string;
};

export type ExportResourceToCommonCartridgeResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export const ExportResourceToCommonCartridgeRequest$inboundSchema: z.ZodType<
  ExportResourceToCommonCartridgeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourceId: z.string(),
});
/** @internal */
export type ExportResourceToCommonCartridgeRequest$Outbound = {
  sourceId: string;
};

/** @internal */
export const ExportResourceToCommonCartridgeRequest$outboundSchema: z.ZodType<
  ExportResourceToCommonCartridgeRequest$Outbound,
  z.ZodTypeDef,
  ExportResourceToCommonCartridgeRequest
> = z.object({
  sourceId: z.string(),
});

export function exportResourceToCommonCartridgeRequestToJSON(
  exportResourceToCommonCartridgeRequest:
    ExportResourceToCommonCartridgeRequest,
): string {
  return JSON.stringify(
    ExportResourceToCommonCartridgeRequest$outboundSchema.parse(
      exportResourceToCommonCartridgeRequest,
    ),
  );
}
export function exportResourceToCommonCartridgeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExportResourceToCommonCartridgeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExportResourceToCommonCartridgeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportResourceToCommonCartridgeRequest' from JSON`,
  );
}

/** @internal */
export const ExportResourceToCommonCartridgeResponse$inboundSchema: z.ZodType<
  ExportResourceToCommonCartridgeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type ExportResourceToCommonCartridgeResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ReadableStream<Uint8Array>;
};

/** @internal */
export const ExportResourceToCommonCartridgeResponse$outboundSchema: z.ZodType<
  ExportResourceToCommonCartridgeResponse$Outbound,
  z.ZodTypeDef,
  ExportResourceToCommonCartridgeResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function exportResourceToCommonCartridgeResponseToJSON(
  exportResourceToCommonCartridgeResponse:
    ExportResourceToCommonCartridgeResponse,
): string {
  return JSON.stringify(
    ExportResourceToCommonCartridgeResponse$outboundSchema.parse(
      exportResourceToCommonCartridgeResponse,
    ),
  );
}
export function exportResourceToCommonCartridgeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ExportResourceToCommonCartridgeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ExportResourceToCommonCartridgeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ExportResourceToCommonCartridgeResponse' from JSON`,
  );
}
