/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetAllComponentResourcesOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetAllComponentResourcesOrderBy = ClosedEnum<
  typeof GetAllComponentResourcesOrderBy
>;

export type GetAllComponentResourcesRequest = {
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetAllComponentResourcesOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetAllComponentResourcesStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetAllComponentResourcesStatus = ClosedEnum<
  typeof GetAllComponentResourcesStatus
>;

export type GetAllComponentResourcesCourseComponent = {
  sourcedId: string;
};

export type GetAllComponentResourcesResource = {
  sourcedId: string;
};

/**
 * Represents a resource associated with a course component.
 */
export type GetAllComponentResourcesComponentResource = {
  sourcedId: string;
  status: GetAllComponentResourcesStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  courseComponent: GetAllComponentResourcesCourseComponent;
  resource: GetAllComponentResourcesResource;
  title: string;
  sortOrder?: number | undefined;
};

/**
 * Collection of Component Resources
 */
export type GetAllComponentResourcesResponseBody = {
  componentResources: Array<GetAllComponentResourcesComponentResource>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetAllComponentResourcesResponse = {
  result: GetAllComponentResourcesResponseBody;
};

/** @internal */
export const GetAllComponentResourcesOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetAllComponentResourcesOrderBy
> = z.nativeEnum(GetAllComponentResourcesOrderBy);
/** @internal */
export const GetAllComponentResourcesOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetAllComponentResourcesOrderBy
> = GetAllComponentResourcesOrderBy$inboundSchema;

/** @internal */
export const GetAllComponentResourcesRequest$inboundSchema: z.ZodType<
  GetAllComponentResourcesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllComponentResourcesOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetAllComponentResourcesRequest$Outbound = {
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetAllComponentResourcesRequest$outboundSchema: z.ZodType<
  GetAllComponentResourcesRequest$Outbound,
  z.ZodTypeDef,
  GetAllComponentResourcesRequest
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllComponentResourcesOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getAllComponentResourcesRequestToJSON(
  getAllComponentResourcesRequest: GetAllComponentResourcesRequest,
): string {
  return JSON.stringify(
    GetAllComponentResourcesRequest$outboundSchema.parse(
      getAllComponentResourcesRequest,
    ),
  );
}
export function getAllComponentResourcesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllComponentResourcesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllComponentResourcesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllComponentResourcesRequest' from JSON`,
  );
}

/** @internal */
export const GetAllComponentResourcesStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetAllComponentResourcesStatus
> = z.nativeEnum(GetAllComponentResourcesStatus);
/** @internal */
export const GetAllComponentResourcesStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetAllComponentResourcesStatus
> = GetAllComponentResourcesStatus$inboundSchema;

/** @internal */
export const GetAllComponentResourcesCourseComponent$inboundSchema: z.ZodType<
  GetAllComponentResourcesCourseComponent,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetAllComponentResourcesCourseComponent$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAllComponentResourcesCourseComponent$outboundSchema: z.ZodType<
  GetAllComponentResourcesCourseComponent$Outbound,
  z.ZodTypeDef,
  GetAllComponentResourcesCourseComponent
> = z.object({
  sourcedId: z.string(),
});

export function getAllComponentResourcesCourseComponentToJSON(
  getAllComponentResourcesCourseComponent:
    GetAllComponentResourcesCourseComponent,
): string {
  return JSON.stringify(
    GetAllComponentResourcesCourseComponent$outboundSchema.parse(
      getAllComponentResourcesCourseComponent,
    ),
  );
}
export function getAllComponentResourcesCourseComponentFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllComponentResourcesCourseComponent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllComponentResourcesCourseComponent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllComponentResourcesCourseComponent' from JSON`,
  );
}

/** @internal */
export const GetAllComponentResourcesResource$inboundSchema: z.ZodType<
  GetAllComponentResourcesResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetAllComponentResourcesResource$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAllComponentResourcesResource$outboundSchema: z.ZodType<
  GetAllComponentResourcesResource$Outbound,
  z.ZodTypeDef,
  GetAllComponentResourcesResource
> = z.object({
  sourcedId: z.string(),
});

export function getAllComponentResourcesResourceToJSON(
  getAllComponentResourcesResource: GetAllComponentResourcesResource,
): string {
  return JSON.stringify(
    GetAllComponentResourcesResource$outboundSchema.parse(
      getAllComponentResourcesResource,
    ),
  );
}
export function getAllComponentResourcesResourceFromJSON(
  jsonString: string,
): SafeParseResult<GetAllComponentResourcesResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllComponentResourcesResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllComponentResourcesResource' from JSON`,
  );
}

/** @internal */
export const GetAllComponentResourcesComponentResource$inboundSchema: z.ZodType<
  GetAllComponentResourcesComponentResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetAllComponentResourcesStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  courseComponent: z.lazy(() =>
    GetAllComponentResourcesCourseComponent$inboundSchema
  ),
  resource: z.lazy(() => GetAllComponentResourcesResource$inboundSchema),
  title: z.string(),
  sortOrder: z.number().default(0),
});
/** @internal */
export type GetAllComponentResourcesComponentResource$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  courseComponent: GetAllComponentResourcesCourseComponent$Outbound;
  resource: GetAllComponentResourcesResource$Outbound;
  title: string;
  sortOrder: number;
};

/** @internal */
export const GetAllComponentResourcesComponentResource$outboundSchema:
  z.ZodType<
    GetAllComponentResourcesComponentResource$Outbound,
    z.ZodTypeDef,
    GetAllComponentResourcesComponentResource
  > = z.object({
    sourcedId: z.string(),
    status: GetAllComponentResourcesStatus$outboundSchema,
    dateLastModified: z.date().transform(v => v.toISOString()).optional(),
    metadata: z.nullable(z.record(z.any())).optional(),
    courseComponent: z.lazy(() =>
      GetAllComponentResourcesCourseComponent$outboundSchema
    ),
    resource: z.lazy(() => GetAllComponentResourcesResource$outboundSchema),
    title: z.string(),
    sortOrder: z.number().default(0),
  });

export function getAllComponentResourcesComponentResourceToJSON(
  getAllComponentResourcesComponentResource:
    GetAllComponentResourcesComponentResource,
): string {
  return JSON.stringify(
    GetAllComponentResourcesComponentResource$outboundSchema.parse(
      getAllComponentResourcesComponentResource,
    ),
  );
}
export function getAllComponentResourcesComponentResourceFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllComponentResourcesComponentResource,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllComponentResourcesComponentResource$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllComponentResourcesComponentResource' from JSON`,
  );
}

/** @internal */
export const GetAllComponentResourcesResponseBody$inboundSchema: z.ZodType<
  GetAllComponentResourcesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  componentResources: z.array(
    z.lazy(() => GetAllComponentResourcesComponentResource$inboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetAllComponentResourcesResponseBody$Outbound = {
  componentResources: Array<GetAllComponentResourcesComponentResource$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetAllComponentResourcesResponseBody$outboundSchema: z.ZodType<
  GetAllComponentResourcesResponseBody$Outbound,
  z.ZodTypeDef,
  GetAllComponentResourcesResponseBody
> = z.object({
  componentResources: z.array(
    z.lazy(() => GetAllComponentResourcesComponentResource$outboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getAllComponentResourcesResponseBodyToJSON(
  getAllComponentResourcesResponseBody: GetAllComponentResourcesResponseBody,
): string {
  return JSON.stringify(
    GetAllComponentResourcesResponseBody$outboundSchema.parse(
      getAllComponentResourcesResponseBody,
    ),
  );
}
export function getAllComponentResourcesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetAllComponentResourcesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllComponentResourcesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllComponentResourcesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAllComponentResourcesResponse$inboundSchema: z.ZodType<
  GetAllComponentResourcesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetAllComponentResourcesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetAllComponentResourcesResponse$Outbound = {
  Result: GetAllComponentResourcesResponseBody$Outbound;
};

/** @internal */
export const GetAllComponentResourcesResponse$outboundSchema: z.ZodType<
  GetAllComponentResourcesResponse$Outbound,
  z.ZodTypeDef,
  GetAllComponentResourcesResponse
> = z.object({
  result: z.lazy(() => GetAllComponentResourcesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getAllComponentResourcesResponseToJSON(
  getAllComponentResourcesResponse: GetAllComponentResourcesResponse,
): string {
  return JSON.stringify(
    GetAllComponentResourcesResponse$outboundSchema.parse(
      getAllComponentResourcesResponse,
    ),
  );
}
export function getAllComponentResourcesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllComponentResourcesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllComponentResourcesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllComponentResourcesResponse' from JSON`,
  );
}
