/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetAllEnrollmentsOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetAllEnrollmentsOrderBy = ClosedEnum<
  typeof GetAllEnrollmentsOrderBy
>;

export type GetAllEnrollmentsRequest = {
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetAllEnrollmentsOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetAllEnrollmentsStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetAllEnrollmentsStatus = ClosedEnum<
  typeof GetAllEnrollmentsStatus
>;

export const GetAllEnrollmentsRole = {
  Administrator: "administrator",
  Proctor: "proctor",
  Student: "student",
  Teacher: "teacher",
} as const;
export type GetAllEnrollmentsRole = ClosedEnum<typeof GetAllEnrollmentsRole>;

export type GetAllEnrollmentsUser = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetAllEnrollmentsClass = {
  href: string;
  sourcedId: string;
  type: string;
};

/**
 * Represents an enrollment.
 */
export type GetAllEnrollmentsEnrollment = {
  sourcedId: string;
  status: GetAllEnrollmentsStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  role: GetAllEnrollmentsRole;
  primary: boolean;
  beginDate: string | null;
  endDate: string | null;
  user: GetAllEnrollmentsUser;
  class: GetAllEnrollmentsClass;
};

/**
 * Successful response
 */
export type GetAllEnrollmentsResponseBody = {
  enrollments: Array<GetAllEnrollmentsEnrollment>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetAllEnrollmentsResponse = {
  result: GetAllEnrollmentsResponseBody;
};

/** @internal */
export const GetAllEnrollmentsOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsOrderBy
> = z.nativeEnum(GetAllEnrollmentsOrderBy);

/** @internal */
export const GetAllEnrollmentsOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsOrderBy
> = GetAllEnrollmentsOrderBy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsOrderBy$ {
  /** @deprecated use `GetAllEnrollmentsOrderBy$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsOrderBy$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsOrderBy$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsOrderBy$outboundSchema;
}

/** @internal */
export const GetAllEnrollmentsRequest$inboundSchema: z.ZodType<
  GetAllEnrollmentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllEnrollmentsOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

/** @internal */
export type GetAllEnrollmentsRequest$Outbound = {
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetAllEnrollmentsRequest$outboundSchema: z.ZodType<
  GetAllEnrollmentsRequest$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsRequest
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllEnrollmentsOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsRequest$ {
  /** @deprecated use `GetAllEnrollmentsRequest$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsRequest$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsRequest$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsRequest$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsRequest$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsRequest$Outbound;
}

export function getAllEnrollmentsRequestToJSON(
  getAllEnrollmentsRequest: GetAllEnrollmentsRequest,
): string {
  return JSON.stringify(
    GetAllEnrollmentsRequest$outboundSchema.parse(getAllEnrollmentsRequest),
  );
}

export function getAllEnrollmentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsRequest' from JSON`,
  );
}

/** @internal */
export const GetAllEnrollmentsStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsStatus
> = z.nativeEnum(GetAllEnrollmentsStatus);

/** @internal */
export const GetAllEnrollmentsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsStatus
> = GetAllEnrollmentsStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsStatus$ {
  /** @deprecated use `GetAllEnrollmentsStatus$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsStatus$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsStatus$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsStatus$outboundSchema;
}

/** @internal */
export const GetAllEnrollmentsRole$inboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsRole
> = z.nativeEnum(GetAllEnrollmentsRole);

/** @internal */
export const GetAllEnrollmentsRole$outboundSchema: z.ZodNativeEnum<
  typeof GetAllEnrollmentsRole
> = GetAllEnrollmentsRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsRole$ {
  /** @deprecated use `GetAllEnrollmentsRole$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsRole$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsRole$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsRole$outboundSchema;
}

/** @internal */
export const GetAllEnrollmentsUser$inboundSchema: z.ZodType<
  GetAllEnrollmentsUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

/** @internal */
export type GetAllEnrollmentsUser$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetAllEnrollmentsUser$outboundSchema: z.ZodType<
  GetAllEnrollmentsUser$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsUser
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsUser$ {
  /** @deprecated use `GetAllEnrollmentsUser$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsUser$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsUser$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsUser$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsUser$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsUser$Outbound;
}

export function getAllEnrollmentsUserToJSON(
  getAllEnrollmentsUser: GetAllEnrollmentsUser,
): string {
  return JSON.stringify(
    GetAllEnrollmentsUser$outboundSchema.parse(getAllEnrollmentsUser),
  );
}

export function getAllEnrollmentsUserFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsUser' from JSON`,
  );
}

/** @internal */
export const GetAllEnrollmentsClass$inboundSchema: z.ZodType<
  GetAllEnrollmentsClass,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

/** @internal */
export type GetAllEnrollmentsClass$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetAllEnrollmentsClass$outboundSchema: z.ZodType<
  GetAllEnrollmentsClass$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsClass
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsClass$ {
  /** @deprecated use `GetAllEnrollmentsClass$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsClass$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsClass$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsClass$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsClass$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsClass$Outbound;
}

export function getAllEnrollmentsClassToJSON(
  getAllEnrollmentsClass: GetAllEnrollmentsClass,
): string {
  return JSON.stringify(
    GetAllEnrollmentsClass$outboundSchema.parse(getAllEnrollmentsClass),
  );
}

export function getAllEnrollmentsClassFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsClass, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsClass$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsClass' from JSON`,
  );
}

/** @internal */
export const GetAllEnrollmentsEnrollment$inboundSchema: z.ZodType<
  GetAllEnrollmentsEnrollment,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetAllEnrollmentsStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  role: GetAllEnrollmentsRole$inboundSchema,
  primary: z.boolean(),
  beginDate: z.nullable(z.string()),
  endDate: z.nullable(z.string()),
  user: z.lazy(() => GetAllEnrollmentsUser$inboundSchema),
  class: z.lazy(() => GetAllEnrollmentsClass$inboundSchema),
});

/** @internal */
export type GetAllEnrollmentsEnrollment$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  role: string;
  primary: boolean;
  beginDate: string | null;
  endDate: string | null;
  user: GetAllEnrollmentsUser$Outbound;
  class: GetAllEnrollmentsClass$Outbound;
};

/** @internal */
export const GetAllEnrollmentsEnrollment$outboundSchema: z.ZodType<
  GetAllEnrollmentsEnrollment$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsEnrollment
> = z.object({
  sourcedId: z.string(),
  status: GetAllEnrollmentsStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  role: GetAllEnrollmentsRole$outboundSchema,
  primary: z.boolean(),
  beginDate: z.nullable(z.string()),
  endDate: z.nullable(z.string()),
  user: z.lazy(() => GetAllEnrollmentsUser$outboundSchema),
  class: z.lazy(() => GetAllEnrollmentsClass$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsEnrollment$ {
  /** @deprecated use `GetAllEnrollmentsEnrollment$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsEnrollment$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsEnrollment$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsEnrollment$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsEnrollment$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsEnrollment$Outbound;
}

export function getAllEnrollmentsEnrollmentToJSON(
  getAllEnrollmentsEnrollment: GetAllEnrollmentsEnrollment,
): string {
  return JSON.stringify(
    GetAllEnrollmentsEnrollment$outboundSchema.parse(
      getAllEnrollmentsEnrollment,
    ),
  );
}

export function getAllEnrollmentsEnrollmentFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsEnrollment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsEnrollment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsEnrollment' from JSON`,
  );
}

/** @internal */
export const GetAllEnrollmentsResponseBody$inboundSchema: z.ZodType<
  GetAllEnrollmentsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  enrollments: z.array(z.lazy(() => GetAllEnrollmentsEnrollment$inboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

/** @internal */
export type GetAllEnrollmentsResponseBody$Outbound = {
  enrollments: Array<GetAllEnrollmentsEnrollment$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetAllEnrollmentsResponseBody$outboundSchema: z.ZodType<
  GetAllEnrollmentsResponseBody$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsResponseBody
> = z.object({
  enrollments: z.array(
    z.lazy(() => GetAllEnrollmentsEnrollment$outboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsResponseBody$ {
  /** @deprecated use `GetAllEnrollmentsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsResponseBody$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsResponseBody$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsResponseBody$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsResponseBody$Outbound;
}

export function getAllEnrollmentsResponseBodyToJSON(
  getAllEnrollmentsResponseBody: GetAllEnrollmentsResponseBody,
): string {
  return JSON.stringify(
    GetAllEnrollmentsResponseBody$outboundSchema.parse(
      getAllEnrollmentsResponseBody,
    ),
  );
}

export function getAllEnrollmentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAllEnrollmentsResponse$inboundSchema: z.ZodType<
  GetAllEnrollmentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetAllEnrollmentsResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type GetAllEnrollmentsResponse$Outbound = {
  Result: GetAllEnrollmentsResponseBody$Outbound;
};

/** @internal */
export const GetAllEnrollmentsResponse$outboundSchema: z.ZodType<
  GetAllEnrollmentsResponse$Outbound,
  z.ZodTypeDef,
  GetAllEnrollmentsResponse
> = z.object({
  result: z.lazy(() => GetAllEnrollmentsResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllEnrollmentsResponse$ {
  /** @deprecated use `GetAllEnrollmentsResponse$inboundSchema` instead. */
  export const inboundSchema = GetAllEnrollmentsResponse$inboundSchema;
  /** @deprecated use `GetAllEnrollmentsResponse$outboundSchema` instead. */
  export const outboundSchema = GetAllEnrollmentsResponse$outboundSchema;
  /** @deprecated use `GetAllEnrollmentsResponse$Outbound` instead. */
  export type Outbound = GetAllEnrollmentsResponse$Outbound;
}

export function getAllEnrollmentsResponseToJSON(
  getAllEnrollmentsResponse: GetAllEnrollmentsResponse,
): string {
  return JSON.stringify(
    GetAllEnrollmentsResponse$outboundSchema.parse(getAllEnrollmentsResponse),
  );
}

export function getAllEnrollmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllEnrollmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllEnrollmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllEnrollmentsResponse' from JSON`,
  );
}
