/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetAllResourcesOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetAllResourcesOrderBy = ClosedEnum<typeof GetAllResourcesOrderBy>;

export type GetAllResourcesRequest = {
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetAllResourcesOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetAllResourcesStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetAllResourcesStatus = ClosedEnum<typeof GetAllResourcesStatus>;

export const GetAllResourcesRole = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
export type GetAllResourcesRole = ClosedEnum<typeof GetAllResourcesRole>;

export const GetAllResourcesImportance = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
export type GetAllResourcesImportance = ClosedEnum<
  typeof GetAllResourcesImportance
>;

/**
 * Represents a digital resource of some kind.
 */
export type GetAllResourcesResource = {
  sourcedId: string;
  status: GetAllResourcesStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  roles?: Array<GetAllResourcesRole> | undefined;
  importance?: GetAllResourcesImportance | undefined;
  vendorResourceId: string;
  vendorId?: string | null | undefined;
  applicationId?: string | null | undefined;
};

/**
 * Successful response containing a collection of resources
 */
export type GetAllResourcesResponseBody = {
  resources: Array<GetAllResourcesResource>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetAllResourcesResponse = {
  result: GetAllResourcesResponseBody;
};

/** @internal */
export const GetAllResourcesOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesOrderBy
> = z.nativeEnum(GetAllResourcesOrderBy);
/** @internal */
export const GetAllResourcesOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesOrderBy
> = GetAllResourcesOrderBy$inboundSchema;

/** @internal */
export const GetAllResourcesRequest$inboundSchema: z.ZodType<
  GetAllResourcesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllResourcesOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetAllResourcesRequest$Outbound = {
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetAllResourcesRequest$outboundSchema: z.ZodType<
  GetAllResourcesRequest$Outbound,
  z.ZodTypeDef,
  GetAllResourcesRequest
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllResourcesOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getAllResourcesRequestToJSON(
  getAllResourcesRequest: GetAllResourcesRequest,
): string {
  return JSON.stringify(
    GetAllResourcesRequest$outboundSchema.parse(getAllResourcesRequest),
  );
}
export function getAllResourcesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllResourcesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllResourcesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllResourcesRequest' from JSON`,
  );
}

/** @internal */
export const GetAllResourcesStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesStatus
> = z.nativeEnum(GetAllResourcesStatus);
/** @internal */
export const GetAllResourcesStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesStatus
> = GetAllResourcesStatus$inboundSchema;

/** @internal */
export const GetAllResourcesRole$inboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesRole
> = z.nativeEnum(GetAllResourcesRole);
/** @internal */
export const GetAllResourcesRole$outboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesRole
> = GetAllResourcesRole$inboundSchema;

/** @internal */
export const GetAllResourcesImportance$inboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesImportance
> = z.nativeEnum(GetAllResourcesImportance);
/** @internal */
export const GetAllResourcesImportance$outboundSchema: z.ZodNativeEnum<
  typeof GetAllResourcesImportance
> = GetAllResourcesImportance$inboundSchema;

/** @internal */
export const GetAllResourcesResource$inboundSchema: z.ZodType<
  GetAllResourcesResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetAllResourcesStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  roles: z.array(GetAllResourcesRole$inboundSchema).optional(),
  importance: GetAllResourcesImportance$inboundSchema.optional(),
  vendorResourceId: z.string(),
  vendorId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
});
/** @internal */
export type GetAllResourcesResource$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  roles?: Array<string> | undefined;
  importance?: string | undefined;
  vendorResourceId: string;
  vendorId?: string | null | undefined;
  applicationId?: string | null | undefined;
};

/** @internal */
export const GetAllResourcesResource$outboundSchema: z.ZodType<
  GetAllResourcesResource$Outbound,
  z.ZodTypeDef,
  GetAllResourcesResource
> = z.object({
  sourcedId: z.string(),
  status: GetAllResourcesStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  roles: z.array(GetAllResourcesRole$outboundSchema).optional(),
  importance: GetAllResourcesImportance$outboundSchema.optional(),
  vendorResourceId: z.string(),
  vendorId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
});

export function getAllResourcesResourceToJSON(
  getAllResourcesResource: GetAllResourcesResource,
): string {
  return JSON.stringify(
    GetAllResourcesResource$outboundSchema.parse(getAllResourcesResource),
  );
}
export function getAllResourcesResourceFromJSON(
  jsonString: string,
): SafeParseResult<GetAllResourcesResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllResourcesResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllResourcesResource' from JSON`,
  );
}

/** @internal */
export const GetAllResourcesResponseBody$inboundSchema: z.ZodType<
  GetAllResourcesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  resources: z.array(z.lazy(() => GetAllResourcesResource$inboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetAllResourcesResponseBody$Outbound = {
  resources: Array<GetAllResourcesResource$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetAllResourcesResponseBody$outboundSchema: z.ZodType<
  GetAllResourcesResponseBody$Outbound,
  z.ZodTypeDef,
  GetAllResourcesResponseBody
> = z.object({
  resources: z.array(z.lazy(() => GetAllResourcesResource$outboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getAllResourcesResponseBodyToJSON(
  getAllResourcesResponseBody: GetAllResourcesResponseBody,
): string {
  return JSON.stringify(
    GetAllResourcesResponseBody$outboundSchema.parse(
      getAllResourcesResponseBody,
    ),
  );
}
export function getAllResourcesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetAllResourcesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllResourcesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllResourcesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAllResourcesResponse$inboundSchema: z.ZodType<
  GetAllResourcesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetAllResourcesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetAllResourcesResponse$Outbound = {
  Result: GetAllResourcesResponseBody$Outbound;
};

/** @internal */
export const GetAllResourcesResponse$outboundSchema: z.ZodType<
  GetAllResourcesResponse$Outbound,
  z.ZodTypeDef,
  GetAllResourcesResponse
> = z.object({
  result: z.lazy(() => GetAllResourcesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getAllResourcesResponseToJSON(
  getAllResourcesResponse: GetAllResourcesResponse,
): string {
  return JSON.stringify(
    GetAllResourcesResponse$outboundSchema.parse(getAllResourcesResponse),
  );
}
export function getAllResourcesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllResourcesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllResourcesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllResourcesResponse' from JSON`,
  );
}
