/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetAllAssessmentLineItemsOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetAllAssessmentLineItemsOrderBy = ClosedEnum<
  typeof GetAllAssessmentLineItemsOrderBy
>;

export type GetAllAssessmentLineItemsRequest = {
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetAllAssessmentLineItemsOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetAllAssessmentLineItemsStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetAllAssessmentLineItemsStatus = ClosedEnum<
  typeof GetAllAssessmentLineItemsStatus
>;

export type GetAllAssessmentLineItemsClass = {
  sourcedId: string;
};

/**
 * Represents a parent assessment line item.
 */
export type ParentAssessmentLineItem = {
  sourcedId: string;
};

/**
 * Represents a score scale.
 */
export type GetAllAssessmentLineItemsScoreScale = {
  sourcedId: string;
};

/**
 * Reference to the Component that this assessment line item is associated with.
 */
export type Component = {
  sourcedId: string;
};

/**
 * Reference to the Component Resource that this assessment line item is associated with.
 */
export type GetAllAssessmentLineItemsComponentResource = {
  sourcedId: string;
};

/**
 * Represents an assessment line item.
 */
export type GetAllAssessmentLineItemsAssessmentLineItem = {
  sourcedId?: string | undefined;
  status: GetAllAssessmentLineItemsStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  description?: string | null | undefined;
  class?: GetAllAssessmentLineItemsClass | null | undefined;
  /**
   * Represents a parent assessment line item.
   */
  parentAssessmentLineItem?: ParentAssessmentLineItem | null | undefined;
  /**
   * Represents a score scale.
   */
  scoreScale?: GetAllAssessmentLineItemsScoreScale | null | undefined;
  resultValueMin?: number | null | undefined;
  resultValueMax?: number | null | undefined;
  /**
   * Reference to the Component that this assessment line item is associated with.
   */
  component?: Component | null | undefined;
  /**
   * Reference to the Component Resource that this assessment line item is associated with.
   */
  componentResource?:
    | GetAllAssessmentLineItemsComponentResource
    | null
    | undefined;
  /**
   * Represents a learning objective set.
   */
  learningObjectiveSet?:
    | Array<components.LearningObjectiveSet>
    | null
    | undefined;
};

/**
 * Successful response containing a collection of assessment line items
 */
export type GetAllAssessmentLineItemsResponseBody = {
  assessmentLineItems: Array<GetAllAssessmentLineItemsAssessmentLineItem>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetAllAssessmentLineItemsResponse = {
  result: GetAllAssessmentLineItemsResponseBody;
};

/** @internal */
export const GetAllAssessmentLineItemsOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetAllAssessmentLineItemsOrderBy
> = z.nativeEnum(GetAllAssessmentLineItemsOrderBy);
/** @internal */
export const GetAllAssessmentLineItemsOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetAllAssessmentLineItemsOrderBy
> = GetAllAssessmentLineItemsOrderBy$inboundSchema;

/** @internal */
export const GetAllAssessmentLineItemsRequest$inboundSchema: z.ZodType<
  GetAllAssessmentLineItemsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllAssessmentLineItemsOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetAllAssessmentLineItemsRequest$Outbound = {
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetAllAssessmentLineItemsRequest$outboundSchema: z.ZodType<
  GetAllAssessmentLineItemsRequest$Outbound,
  z.ZodTypeDef,
  GetAllAssessmentLineItemsRequest
> = z.object({
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetAllAssessmentLineItemsOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getAllAssessmentLineItemsRequestToJSON(
  getAllAssessmentLineItemsRequest: GetAllAssessmentLineItemsRequest,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsRequest$outboundSchema.parse(
      getAllAssessmentLineItemsRequest,
    ),
  );
}
export function getAllAssessmentLineItemsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAllAssessmentLineItemsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllAssessmentLineItemsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllAssessmentLineItemsRequest' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetAllAssessmentLineItemsStatus
> = z.nativeEnum(GetAllAssessmentLineItemsStatus);
/** @internal */
export const GetAllAssessmentLineItemsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetAllAssessmentLineItemsStatus
> = GetAllAssessmentLineItemsStatus$inboundSchema;

/** @internal */
export const GetAllAssessmentLineItemsClass$inboundSchema: z.ZodType<
  GetAllAssessmentLineItemsClass,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetAllAssessmentLineItemsClass$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAllAssessmentLineItemsClass$outboundSchema: z.ZodType<
  GetAllAssessmentLineItemsClass$Outbound,
  z.ZodTypeDef,
  GetAllAssessmentLineItemsClass
> = z.object({
  sourcedId: z.string(),
});

export function getAllAssessmentLineItemsClassToJSON(
  getAllAssessmentLineItemsClass: GetAllAssessmentLineItemsClass,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsClass$outboundSchema.parse(
      getAllAssessmentLineItemsClass,
    ),
  );
}
export function getAllAssessmentLineItemsClassFromJSON(
  jsonString: string,
): SafeParseResult<GetAllAssessmentLineItemsClass, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllAssessmentLineItemsClass$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllAssessmentLineItemsClass' from JSON`,
  );
}

/** @internal */
export const ParentAssessmentLineItem$inboundSchema: z.ZodType<
  ParentAssessmentLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type ParentAssessmentLineItem$Outbound = {
  sourcedId: string;
};

/** @internal */
export const ParentAssessmentLineItem$outboundSchema: z.ZodType<
  ParentAssessmentLineItem$Outbound,
  z.ZodTypeDef,
  ParentAssessmentLineItem
> = z.object({
  sourcedId: z.string(),
});

export function parentAssessmentLineItemToJSON(
  parentAssessmentLineItem: ParentAssessmentLineItem,
): string {
  return JSON.stringify(
    ParentAssessmentLineItem$outboundSchema.parse(parentAssessmentLineItem),
  );
}
export function parentAssessmentLineItemFromJSON(
  jsonString: string,
): SafeParseResult<ParentAssessmentLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParentAssessmentLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParentAssessmentLineItem' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsScoreScale$inboundSchema: z.ZodType<
  GetAllAssessmentLineItemsScoreScale,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetAllAssessmentLineItemsScoreScale$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAllAssessmentLineItemsScoreScale$outboundSchema: z.ZodType<
  GetAllAssessmentLineItemsScoreScale$Outbound,
  z.ZodTypeDef,
  GetAllAssessmentLineItemsScoreScale
> = z.object({
  sourcedId: z.string(),
});

export function getAllAssessmentLineItemsScoreScaleToJSON(
  getAllAssessmentLineItemsScoreScale: GetAllAssessmentLineItemsScoreScale,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsScoreScale$outboundSchema.parse(
      getAllAssessmentLineItemsScoreScale,
    ),
  );
}
export function getAllAssessmentLineItemsScoreScaleFromJSON(
  jsonString: string,
): SafeParseResult<GetAllAssessmentLineItemsScoreScale, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllAssessmentLineItemsScoreScale$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllAssessmentLineItemsScoreScale' from JSON`,
  );
}

/** @internal */
export const Component$inboundSchema: z.ZodType<
  Component,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type Component$Outbound = {
  sourcedId: string;
};

/** @internal */
export const Component$outboundSchema: z.ZodType<
  Component$Outbound,
  z.ZodTypeDef,
  Component
> = z.object({
  sourcedId: z.string(),
});

export function componentToJSON(component: Component): string {
  return JSON.stringify(Component$outboundSchema.parse(component));
}
export function componentFromJSON(
  jsonString: string,
): SafeParseResult<Component, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Component$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Component' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsComponentResource$inboundSchema:
  z.ZodType<GetAllAssessmentLineItemsComponentResource, z.ZodTypeDef, unknown> =
    z.object({
      sourcedId: z.string(),
    });
/** @internal */
export type GetAllAssessmentLineItemsComponentResource$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetAllAssessmentLineItemsComponentResource$outboundSchema:
  z.ZodType<
    GetAllAssessmentLineItemsComponentResource$Outbound,
    z.ZodTypeDef,
    GetAllAssessmentLineItemsComponentResource
  > = z.object({
    sourcedId: z.string(),
  });

export function getAllAssessmentLineItemsComponentResourceToJSON(
  getAllAssessmentLineItemsComponentResource:
    GetAllAssessmentLineItemsComponentResource,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsComponentResource$outboundSchema.parse(
      getAllAssessmentLineItemsComponentResource,
    ),
  );
}
export function getAllAssessmentLineItemsComponentResourceFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllAssessmentLineItemsComponentResource,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllAssessmentLineItemsComponentResource$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllAssessmentLineItemsComponentResource' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsAssessmentLineItem$inboundSchema:
  z.ZodType<
    GetAllAssessmentLineItemsAssessmentLineItem,
    z.ZodTypeDef,
    unknown
  > = z.object({
    sourcedId: z.string().optional(),
    status: GetAllAssessmentLineItemsStatus$inboundSchema,
    dateLastModified: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    metadata: z.nullable(z.record(z.any())).optional(),
    title: z.string(),
    description: z.nullable(z.string()).optional(),
    class: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsClass$inboundSchema),
    ).optional(),
    parentAssessmentLineItem: z.nullable(
      z.lazy(() => ParentAssessmentLineItem$inboundSchema),
    ).optional(),
    scoreScale: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsScoreScale$inboundSchema),
    ).optional(),
    resultValueMin: z.nullable(z.number()).optional(),
    resultValueMax: z.nullable(z.number()).optional(),
    component: z.nullable(z.lazy(() => Component$inboundSchema)).optional(),
    componentResource: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsComponentResource$inboundSchema),
    ).optional(),
    learningObjectiveSet: z.nullable(
      z.array(components.LearningObjectiveSet$inboundSchema),
    ).optional(),
  });
/** @internal */
export type GetAllAssessmentLineItemsAssessmentLineItem$Outbound = {
  sourcedId?: string | undefined;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  description?: string | null | undefined;
  class?: GetAllAssessmentLineItemsClass$Outbound | null | undefined;
  parentAssessmentLineItem?:
    | ParentAssessmentLineItem$Outbound
    | null
    | undefined;
  scoreScale?: GetAllAssessmentLineItemsScoreScale$Outbound | null | undefined;
  resultValueMin?: number | null | undefined;
  resultValueMax?: number | null | undefined;
  component?: Component$Outbound | null | undefined;
  componentResource?:
    | GetAllAssessmentLineItemsComponentResource$Outbound
    | null
    | undefined;
  learningObjectiveSet?:
    | Array<components.LearningObjectiveSet$Outbound>
    | null
    | undefined;
};

/** @internal */
export const GetAllAssessmentLineItemsAssessmentLineItem$outboundSchema:
  z.ZodType<
    GetAllAssessmentLineItemsAssessmentLineItem$Outbound,
    z.ZodTypeDef,
    GetAllAssessmentLineItemsAssessmentLineItem
  > = z.object({
    sourcedId: z.string().optional(),
    status: GetAllAssessmentLineItemsStatus$outboundSchema,
    dateLastModified: z.date().transform(v => v.toISOString()).optional(),
    metadata: z.nullable(z.record(z.any())).optional(),
    title: z.string(),
    description: z.nullable(z.string()).optional(),
    class: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsClass$outboundSchema),
    ).optional(),
    parentAssessmentLineItem: z.nullable(
      z.lazy(() => ParentAssessmentLineItem$outboundSchema),
    ).optional(),
    scoreScale: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsScoreScale$outboundSchema),
    ).optional(),
    resultValueMin: z.nullable(z.number()).optional(),
    resultValueMax: z.nullable(z.number()).optional(),
    component: z.nullable(z.lazy(() => Component$outboundSchema)).optional(),
    componentResource: z.nullable(
      z.lazy(() => GetAllAssessmentLineItemsComponentResource$outboundSchema),
    ).optional(),
    learningObjectiveSet: z.nullable(
      z.array(components.LearningObjectiveSet$outboundSchema),
    ).optional(),
  });

export function getAllAssessmentLineItemsAssessmentLineItemToJSON(
  getAllAssessmentLineItemsAssessmentLineItem:
    GetAllAssessmentLineItemsAssessmentLineItem,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsAssessmentLineItem$outboundSchema.parse(
      getAllAssessmentLineItemsAssessmentLineItem,
    ),
  );
}
export function getAllAssessmentLineItemsAssessmentLineItemFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllAssessmentLineItemsAssessmentLineItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllAssessmentLineItemsAssessmentLineItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllAssessmentLineItemsAssessmentLineItem' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsResponseBody$inboundSchema: z.ZodType<
  GetAllAssessmentLineItemsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  assessmentLineItems: z.array(
    z.lazy(() => GetAllAssessmentLineItemsAssessmentLineItem$inboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetAllAssessmentLineItemsResponseBody$Outbound = {
  assessmentLineItems: Array<
    GetAllAssessmentLineItemsAssessmentLineItem$Outbound
  >;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetAllAssessmentLineItemsResponseBody$outboundSchema: z.ZodType<
  GetAllAssessmentLineItemsResponseBody$Outbound,
  z.ZodTypeDef,
  GetAllAssessmentLineItemsResponseBody
> = z.object({
  assessmentLineItems: z.array(
    z.lazy(() => GetAllAssessmentLineItemsAssessmentLineItem$outboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getAllAssessmentLineItemsResponseBodyToJSON(
  getAllAssessmentLineItemsResponseBody: GetAllAssessmentLineItemsResponseBody,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsResponseBody$outboundSchema.parse(
      getAllAssessmentLineItemsResponseBody,
    ),
  );
}
export function getAllAssessmentLineItemsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetAllAssessmentLineItemsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllAssessmentLineItemsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllAssessmentLineItemsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetAllAssessmentLineItemsResponse$inboundSchema: z.ZodType<
  GetAllAssessmentLineItemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetAllAssessmentLineItemsResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetAllAssessmentLineItemsResponse$Outbound = {
  Result: GetAllAssessmentLineItemsResponseBody$Outbound;
};

/** @internal */
export const GetAllAssessmentLineItemsResponse$outboundSchema: z.ZodType<
  GetAllAssessmentLineItemsResponse$Outbound,
  z.ZodTypeDef,
  GetAllAssessmentLineItemsResponse
> = z.object({
  result: z.lazy(() => GetAllAssessmentLineItemsResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getAllAssessmentLineItemsResponseToJSON(
  getAllAssessmentLineItemsResponse: GetAllAssessmentLineItemsResponse,
): string {
  return JSON.stringify(
    GetAllAssessmentLineItemsResponse$outboundSchema.parse(
      getAllAssessmentLineItemsResponse,
    ),
  );
}
export function getAllAssessmentLineItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllAssessmentLineItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllAssessmentLineItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllAssessmentLineItemsResponse' from JSON`,
  );
}
