/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetClassesForCourseOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetClassesForCourseOrderBy = ClosedEnum<
  typeof GetClassesForCourseOrderBy
>;

export type GetClassesForCourseRequest = {
  /**
   * The sourcedId of the course
   */
  courseSourcedId: string;
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetClassesForCourseOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetClassesForCourseStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetClassesForCourseStatus = ClosedEnum<
  typeof GetClassesForCourseStatus
>;

export const GetClassesForCourseClassType = {
  Homeroom: "homeroom",
  Scheduled: "scheduled",
} as const;
export type GetClassesForCourseClassType = ClosedEnum<
  typeof GetClassesForCourseClassType
>;

export type GetClassesForCourseCourse = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetClassesForCourseSchool = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetClassesForCourseTerm = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetClassesForCourseResource = {
  href: string;
  sourcedId: string;
  type: string;
};

/**
 * Represents a class.
 */
export type GetClassesForCourseClass = {
  sourcedId: string;
  status: GetClassesForCourseStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  classCode: string | null;
  classType: GetClassesForCourseClassType;
  location: string | null;
  grades?: Array<string> | undefined;
  subjects?: Array<string> | undefined;
  course: GetClassesForCourseCourse | null;
  school: GetClassesForCourseSchool | null;
  terms: Array<GetClassesForCourseTerm>;
  subjectCodes?: Array<string> | undefined;
  periods?: Array<string> | undefined;
  resources?: Array<GetClassesForCourseResource> | undefined;
};

/**
 * Collection of Classes for Course
 */
export type GetClassesForCourseResponseBody = {
  classes: Array<GetClassesForCourseClass>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetClassesForCourseResponse = {
  result: GetClassesForCourseResponseBody;
};

/** @internal */
export const GetClassesForCourseOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseOrderBy
> = z.nativeEnum(GetClassesForCourseOrderBy);
/** @internal */
export const GetClassesForCourseOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseOrderBy
> = GetClassesForCourseOrderBy$inboundSchema;

/** @internal */
export const GetClassesForCourseRequest$inboundSchema: z.ZodType<
  GetClassesForCourseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  courseSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetClassesForCourseOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetClassesForCourseRequest$Outbound = {
  courseSourcedId: string;
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetClassesForCourseRequest$outboundSchema: z.ZodType<
  GetClassesForCourseRequest$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseRequest
> = z.object({
  courseSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetClassesForCourseOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getClassesForCourseRequestToJSON(
  getClassesForCourseRequest: GetClassesForCourseRequest,
): string {
  return JSON.stringify(
    GetClassesForCourseRequest$outboundSchema.parse(getClassesForCourseRequest),
  );
}
export function getClassesForCourseRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseRequest' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseStatus
> = z.nativeEnum(GetClassesForCourseStatus);
/** @internal */
export const GetClassesForCourseStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseStatus
> = GetClassesForCourseStatus$inboundSchema;

/** @internal */
export const GetClassesForCourseClassType$inboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseClassType
> = z.nativeEnum(GetClassesForCourseClassType);
/** @internal */
export const GetClassesForCourseClassType$outboundSchema: z.ZodNativeEnum<
  typeof GetClassesForCourseClassType
> = GetClassesForCourseClassType$inboundSchema;

/** @internal */
export const GetClassesForCourseCourse$inboundSchema: z.ZodType<
  GetClassesForCourseCourse,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetClassesForCourseCourse$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetClassesForCourseCourse$outboundSchema: z.ZodType<
  GetClassesForCourseCourse$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseCourse
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getClassesForCourseCourseToJSON(
  getClassesForCourseCourse: GetClassesForCourseCourse,
): string {
  return JSON.stringify(
    GetClassesForCourseCourse$outboundSchema.parse(getClassesForCourseCourse),
  );
}
export function getClassesForCourseCourseFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseCourse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseCourse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseCourse' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseSchool$inboundSchema: z.ZodType<
  GetClassesForCourseSchool,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetClassesForCourseSchool$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetClassesForCourseSchool$outboundSchema: z.ZodType<
  GetClassesForCourseSchool$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseSchool
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getClassesForCourseSchoolToJSON(
  getClassesForCourseSchool: GetClassesForCourseSchool,
): string {
  return JSON.stringify(
    GetClassesForCourseSchool$outboundSchema.parse(getClassesForCourseSchool),
  );
}
export function getClassesForCourseSchoolFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseSchool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseSchool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseSchool' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseTerm$inboundSchema: z.ZodType<
  GetClassesForCourseTerm,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetClassesForCourseTerm$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetClassesForCourseTerm$outboundSchema: z.ZodType<
  GetClassesForCourseTerm$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseTerm
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getClassesForCourseTermToJSON(
  getClassesForCourseTerm: GetClassesForCourseTerm,
): string {
  return JSON.stringify(
    GetClassesForCourseTerm$outboundSchema.parse(getClassesForCourseTerm),
  );
}
export function getClassesForCourseTermFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseTerm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseTerm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseTerm' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseResource$inboundSchema: z.ZodType<
  GetClassesForCourseResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetClassesForCourseResource$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetClassesForCourseResource$outboundSchema: z.ZodType<
  GetClassesForCourseResource$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseResource
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getClassesForCourseResourceToJSON(
  getClassesForCourseResource: GetClassesForCourseResource,
): string {
  return JSON.stringify(
    GetClassesForCourseResource$outboundSchema.parse(
      getClassesForCourseResource,
    ),
  );
}
export function getClassesForCourseResourceFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseResource' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseClass$inboundSchema: z.ZodType<
  GetClassesForCourseClass,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetClassesForCourseStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  classCode: z.nullable(z.string()),
  classType: GetClassesForCourseClassType$inboundSchema,
  location: z.nullable(z.string()),
  grades: z.array(z.string()).optional(),
  subjects: z.array(z.string()).optional(),
  course: z.nullable(z.lazy(() => GetClassesForCourseCourse$inboundSchema)),
  school: z.nullable(z.lazy(() => GetClassesForCourseSchool$inboundSchema)),
  terms: z.array(z.lazy(() => GetClassesForCourseTerm$inboundSchema)),
  subjectCodes: z.array(z.string()).optional(),
  periods: z.array(z.string()).optional(),
  resources: z.array(z.lazy(() => GetClassesForCourseResource$inboundSchema))
    .optional(),
});
/** @internal */
export type GetClassesForCourseClass$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  classCode: string | null;
  classType: string;
  location: string | null;
  grades?: Array<string> | undefined;
  subjects?: Array<string> | undefined;
  course: GetClassesForCourseCourse$Outbound | null;
  school: GetClassesForCourseSchool$Outbound | null;
  terms: Array<GetClassesForCourseTerm$Outbound>;
  subjectCodes?: Array<string> | undefined;
  periods?: Array<string> | undefined;
  resources?: Array<GetClassesForCourseResource$Outbound> | undefined;
};

/** @internal */
export const GetClassesForCourseClass$outboundSchema: z.ZodType<
  GetClassesForCourseClass$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseClass
> = z.object({
  sourcedId: z.string(),
  status: GetClassesForCourseStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  classCode: z.nullable(z.string()),
  classType: GetClassesForCourseClassType$outboundSchema,
  location: z.nullable(z.string()),
  grades: z.array(z.string()).optional(),
  subjects: z.array(z.string()).optional(),
  course: z.nullable(z.lazy(() => GetClassesForCourseCourse$outboundSchema)),
  school: z.nullable(z.lazy(() => GetClassesForCourseSchool$outboundSchema)),
  terms: z.array(z.lazy(() => GetClassesForCourseTerm$outboundSchema)),
  subjectCodes: z.array(z.string()).optional(),
  periods: z.array(z.string()).optional(),
  resources: z.array(z.lazy(() => GetClassesForCourseResource$outboundSchema))
    .optional(),
});

export function getClassesForCourseClassToJSON(
  getClassesForCourseClass: GetClassesForCourseClass,
): string {
  return JSON.stringify(
    GetClassesForCourseClass$outboundSchema.parse(getClassesForCourseClass),
  );
}
export function getClassesForCourseClassFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseClass, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseClass$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseClass' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseResponseBody$inboundSchema: z.ZodType<
  GetClassesForCourseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  classes: z.array(z.lazy(() => GetClassesForCourseClass$inboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetClassesForCourseResponseBody$Outbound = {
  classes: Array<GetClassesForCourseClass$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetClassesForCourseResponseBody$outboundSchema: z.ZodType<
  GetClassesForCourseResponseBody$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseResponseBody
> = z.object({
  classes: z.array(z.lazy(() => GetClassesForCourseClass$outboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getClassesForCourseResponseBodyToJSON(
  getClassesForCourseResponseBody: GetClassesForCourseResponseBody,
): string {
  return JSON.stringify(
    GetClassesForCourseResponseBody$outboundSchema.parse(
      getClassesForCourseResponseBody,
    ),
  );
}
export function getClassesForCourseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseResponseBody' from JSON`,
  );
}

/** @internal */
export const GetClassesForCourseResponse$inboundSchema: z.ZodType<
  GetClassesForCourseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetClassesForCourseResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetClassesForCourseResponse$Outbound = {
  Result: GetClassesForCourseResponseBody$Outbound;
};

/** @internal */
export const GetClassesForCourseResponse$outboundSchema: z.ZodType<
  GetClassesForCourseResponse$Outbound,
  z.ZodTypeDef,
  GetClassesForCourseResponse
> = z.object({
  result: z.lazy(() => GetClassesForCourseResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getClassesForCourseResponseToJSON(
  getClassesForCourseResponse: GetClassesForCourseResponse,
): string {
  return JSON.stringify(
    GetClassesForCourseResponse$outboundSchema.parse(
      getClassesForCourseResponse,
    ),
  );
}
export function getClassesForCourseResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetClassesForCourseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClassesForCourseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClassesForCourseResponse' from JSON`,
  );
}
