/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCategoryRequest = {
  /**
   * The sourcedId of the category
   */
  sourcedId: string;
};

/**
 * Successful response with the category
 */
export type GetCategoryResponse = {
  /**
   * Represents a category.
   */
  category: components.Category;
};

/** @internal */
export const GetCategoryRequest$inboundSchema: z.ZodType<
  GetCategoryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetCategoryRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetCategoryRequest$outboundSchema: z.ZodType<
  GetCategoryRequest$Outbound,
  z.ZodTypeDef,
  GetCategoryRequest
> = z.object({
  sourcedId: z.string(),
});

export function getCategoryRequestToJSON(
  getCategoryRequest: GetCategoryRequest,
): string {
  return JSON.stringify(
    GetCategoryRequest$outboundSchema.parse(getCategoryRequest),
  );
}
export function getCategoryRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCategoryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCategoryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCategoryRequest' from JSON`,
  );
}

/** @internal */
export const GetCategoryResponse$inboundSchema: z.ZodType<
  GetCategoryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  category: components.Category$inboundSchema,
});
/** @internal */
export type GetCategoryResponse$Outbound = {
  category: components.Category$Outbound;
};

/** @internal */
export const GetCategoryResponse$outboundSchema: z.ZodType<
  GetCategoryResponse$Outbound,
  z.ZodTypeDef,
  GetCategoryResponse
> = z.object({
  category: components.Category$outboundSchema,
});

export function getCategoryResponseToJSON(
  getCategoryResponse: GetCategoryResponse,
): string {
  return JSON.stringify(
    GetCategoryResponse$outboundSchema.parse(getCategoryResponse),
  );
}
export function getCategoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCategoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCategoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCategoryResponse' from JSON`,
  );
}
