/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetLineItemsForSchoolOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetLineItemsForSchoolOrderBy = ClosedEnum<
  typeof GetLineItemsForSchoolOrderBy
>;

export type GetLineItemsForSchoolRequest = {
  /**
   * The sourcedId of the school
   */
  sourcedId: string;
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetLineItemsForSchoolOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetLineItemsForSchoolStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetLineItemsForSchoolStatus = ClosedEnum<
  typeof GetLineItemsForSchoolStatus
>;

export type GetLineItemsForSchoolClass = {
  sourcedId: string;
};

export type GetLineItemsForSchoolSchool = {
  sourcedId: string;
};

export type GetLineItemsForSchoolCategory = {
  sourcedId: string;
};

export type GetLineItemsForSchoolGradingPeriod = {
  sourcedId: string;
};

export type GetLineItemsForSchoolAcademicSession = {
  sourcedId: string;
};

export type GetLineItemsForSchoolScoreScale = {
  sourcedId: string;
};

export type GetLineItemsForSchoolLearningObjectiveSet = {
  source: string;
  learningObjectiveIds: Array<string>;
};

/**
 * Represents a line item.
 */
export type GetLineItemsForSchoolLineItem = {
  sourcedId?: string | undefined;
  status?: GetLineItemsForSchoolStatus | undefined;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  description?: string | null | undefined;
  assignDate: Date;
  dueDate: Date;
  class: GetLineItemsForSchoolClass;
  school: GetLineItemsForSchoolSchool;
  category: GetLineItemsForSchoolCategory;
  gradingPeriod?: GetLineItemsForSchoolGradingPeriod | null | undefined;
  academicSession?: GetLineItemsForSchoolAcademicSession | null | undefined;
  scoreScale?: GetLineItemsForSchoolScoreScale | null | undefined;
  resultValueMin?: number | null | undefined;
  resultValueMax?: number | null | undefined;
  learningObjectiveSet?:
    | Array<GetLineItemsForSchoolLearningObjectiveSet>
    | null
    | undefined;
};

/**
 * Successful response containing a collection of line items
 */
export type GetLineItemsForSchoolResponseBody = {
  lineItems: Array<GetLineItemsForSchoolLineItem>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetLineItemsForSchoolResponse = {
  result: GetLineItemsForSchoolResponseBody;
};

/** @internal */
export const GetLineItemsForSchoolOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetLineItemsForSchoolOrderBy
> = z.nativeEnum(GetLineItemsForSchoolOrderBy);
/** @internal */
export const GetLineItemsForSchoolOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetLineItemsForSchoolOrderBy
> = GetLineItemsForSchoolOrderBy$inboundSchema;

/** @internal */
export const GetLineItemsForSchoolRequest$inboundSchema: z.ZodType<
  GetLineItemsForSchoolRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetLineItemsForSchoolOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetLineItemsForSchoolRequest$Outbound = {
  sourcedId: string;
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetLineItemsForSchoolRequest$outboundSchema: z.ZodType<
  GetLineItemsForSchoolRequest$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolRequest
> = z.object({
  sourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetLineItemsForSchoolOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getLineItemsForSchoolRequestToJSON(
  getLineItemsForSchoolRequest: GetLineItemsForSchoolRequest,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolRequest$outboundSchema.parse(
      getLineItemsForSchoolRequest,
    ),
  );
}
export function getLineItemsForSchoolRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolRequest' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetLineItemsForSchoolStatus
> = z.nativeEnum(GetLineItemsForSchoolStatus);
/** @internal */
export const GetLineItemsForSchoolStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetLineItemsForSchoolStatus
> = GetLineItemsForSchoolStatus$inboundSchema;

/** @internal */
export const GetLineItemsForSchoolClass$inboundSchema: z.ZodType<
  GetLineItemsForSchoolClass,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolClass$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolClass$outboundSchema: z.ZodType<
  GetLineItemsForSchoolClass$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolClass
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolClassToJSON(
  getLineItemsForSchoolClass: GetLineItemsForSchoolClass,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolClass$outboundSchema.parse(getLineItemsForSchoolClass),
  );
}
export function getLineItemsForSchoolClassFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolClass, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolClass$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolClass' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolSchool$inboundSchema: z.ZodType<
  GetLineItemsForSchoolSchool,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolSchool$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolSchool$outboundSchema: z.ZodType<
  GetLineItemsForSchoolSchool$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolSchool
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolSchoolToJSON(
  getLineItemsForSchoolSchool: GetLineItemsForSchoolSchool,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolSchool$outboundSchema.parse(
      getLineItemsForSchoolSchool,
    ),
  );
}
export function getLineItemsForSchoolSchoolFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolSchool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolSchool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolSchool' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolCategory$inboundSchema: z.ZodType<
  GetLineItemsForSchoolCategory,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolCategory$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolCategory$outboundSchema: z.ZodType<
  GetLineItemsForSchoolCategory$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolCategory
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolCategoryToJSON(
  getLineItemsForSchoolCategory: GetLineItemsForSchoolCategory,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolCategory$outboundSchema.parse(
      getLineItemsForSchoolCategory,
    ),
  );
}
export function getLineItemsForSchoolCategoryFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolCategory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolCategory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolCategory' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolGradingPeriod$inboundSchema: z.ZodType<
  GetLineItemsForSchoolGradingPeriod,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolGradingPeriod$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolGradingPeriod$outboundSchema: z.ZodType<
  GetLineItemsForSchoolGradingPeriod$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolGradingPeriod
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolGradingPeriodToJSON(
  getLineItemsForSchoolGradingPeriod: GetLineItemsForSchoolGradingPeriod,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolGradingPeriod$outboundSchema.parse(
      getLineItemsForSchoolGradingPeriod,
    ),
  );
}
export function getLineItemsForSchoolGradingPeriodFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolGradingPeriod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetLineItemsForSchoolGradingPeriod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolGradingPeriod' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolAcademicSession$inboundSchema: z.ZodType<
  GetLineItemsForSchoolAcademicSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolAcademicSession$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolAcademicSession$outboundSchema: z.ZodType<
  GetLineItemsForSchoolAcademicSession$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolAcademicSession
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolAcademicSessionToJSON(
  getLineItemsForSchoolAcademicSession: GetLineItemsForSchoolAcademicSession,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolAcademicSession$outboundSchema.parse(
      getLineItemsForSchoolAcademicSession,
    ),
  );
}
export function getLineItemsForSchoolAcademicSessionFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolAcademicSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetLineItemsForSchoolAcademicSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolAcademicSession' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolScoreScale$inboundSchema: z.ZodType<
  GetLineItemsForSchoolScoreScale,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetLineItemsForSchoolScoreScale$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetLineItemsForSchoolScoreScale$outboundSchema: z.ZodType<
  GetLineItemsForSchoolScoreScale$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolScoreScale
> = z.object({
  sourcedId: z.string(),
});

export function getLineItemsForSchoolScoreScaleToJSON(
  getLineItemsForSchoolScoreScale: GetLineItemsForSchoolScoreScale,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolScoreScale$outboundSchema.parse(
      getLineItemsForSchoolScoreScale,
    ),
  );
}
export function getLineItemsForSchoolScoreScaleFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolScoreScale, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolScoreScale$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolScoreScale' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolLearningObjectiveSet$inboundSchema: z.ZodType<
  GetLineItemsForSchoolLearningObjectiveSet,
  z.ZodTypeDef,
  unknown
> = z.object({
  source: z.string(),
  learningObjectiveIds: z.array(z.string()),
});
/** @internal */
export type GetLineItemsForSchoolLearningObjectiveSet$Outbound = {
  source: string;
  learningObjectiveIds: Array<string>;
};

/** @internal */
export const GetLineItemsForSchoolLearningObjectiveSet$outboundSchema:
  z.ZodType<
    GetLineItemsForSchoolLearningObjectiveSet$Outbound,
    z.ZodTypeDef,
    GetLineItemsForSchoolLearningObjectiveSet
  > = z.object({
    source: z.string(),
    learningObjectiveIds: z.array(z.string()),
  });

export function getLineItemsForSchoolLearningObjectiveSetToJSON(
  getLineItemsForSchoolLearningObjectiveSet:
    GetLineItemsForSchoolLearningObjectiveSet,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolLearningObjectiveSet$outboundSchema.parse(
      getLineItemsForSchoolLearningObjectiveSet,
    ),
  );
}
export function getLineItemsForSchoolLearningObjectiveSetFromJSON(
  jsonString: string,
): SafeParseResult<
  GetLineItemsForSchoolLearningObjectiveSet,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetLineItemsForSchoolLearningObjectiveSet$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetLineItemsForSchoolLearningObjectiveSet' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolLineItem$inboundSchema: z.ZodType<
  GetLineItemsForSchoolLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string().optional(),
  status: GetLineItemsForSchoolStatus$inboundSchema.default("active"),
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  description: z.nullable(z.string()).optional(),
  assignDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  dueDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  class: z.lazy(() => GetLineItemsForSchoolClass$inboundSchema),
  school: z.lazy(() => GetLineItemsForSchoolSchool$inboundSchema),
  category: z.lazy(() => GetLineItemsForSchoolCategory$inboundSchema),
  gradingPeriod: z.nullable(
    z.lazy(() => GetLineItemsForSchoolGradingPeriod$inboundSchema),
  ).optional(),
  academicSession: z.nullable(
    z.lazy(() => GetLineItemsForSchoolAcademicSession$inboundSchema),
  ).optional(),
  scoreScale: z.nullable(
    z.lazy(() => GetLineItemsForSchoolScoreScale$inboundSchema),
  ).optional(),
  resultValueMin: z.nullable(z.number()).optional(),
  resultValueMax: z.nullable(z.number()).optional(),
  learningObjectiveSet: z.nullable(
    z.array(
      z.lazy(() => GetLineItemsForSchoolLearningObjectiveSet$inboundSchema),
    ),
  ).optional(),
});
/** @internal */
export type GetLineItemsForSchoolLineItem$Outbound = {
  sourcedId?: string | undefined;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  description?: string | null | undefined;
  assignDate: string;
  dueDate: string;
  class: GetLineItemsForSchoolClass$Outbound;
  school: GetLineItemsForSchoolSchool$Outbound;
  category: GetLineItemsForSchoolCategory$Outbound;
  gradingPeriod?:
    | GetLineItemsForSchoolGradingPeriod$Outbound
    | null
    | undefined;
  academicSession?:
    | GetLineItemsForSchoolAcademicSession$Outbound
    | null
    | undefined;
  scoreScale?: GetLineItemsForSchoolScoreScale$Outbound | null | undefined;
  resultValueMin?: number | null | undefined;
  resultValueMax?: number | null | undefined;
  learningObjectiveSet?:
    | Array<GetLineItemsForSchoolLearningObjectiveSet$Outbound>
    | null
    | undefined;
};

/** @internal */
export const GetLineItemsForSchoolLineItem$outboundSchema: z.ZodType<
  GetLineItemsForSchoolLineItem$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolLineItem
> = z.object({
  sourcedId: z.string().optional(),
  status: GetLineItemsForSchoolStatus$outboundSchema.default("active"),
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  description: z.nullable(z.string()).optional(),
  assignDate: z.date().transform(v => v.toISOString()),
  dueDate: z.date().transform(v => v.toISOString()),
  class: z.lazy(() => GetLineItemsForSchoolClass$outboundSchema),
  school: z.lazy(() => GetLineItemsForSchoolSchool$outboundSchema),
  category: z.lazy(() => GetLineItemsForSchoolCategory$outboundSchema),
  gradingPeriod: z.nullable(
    z.lazy(() => GetLineItemsForSchoolGradingPeriod$outboundSchema),
  ).optional(),
  academicSession: z.nullable(
    z.lazy(() => GetLineItemsForSchoolAcademicSession$outboundSchema),
  ).optional(),
  scoreScale: z.nullable(
    z.lazy(() => GetLineItemsForSchoolScoreScale$outboundSchema),
  ).optional(),
  resultValueMin: z.nullable(z.number()).optional(),
  resultValueMax: z.nullable(z.number()).optional(),
  learningObjectiveSet: z.nullable(
    z.array(z.lazy(() =>
      GetLineItemsForSchoolLearningObjectiveSet$outboundSchema
    )),
  ).optional(),
});

export function getLineItemsForSchoolLineItemToJSON(
  getLineItemsForSchoolLineItem: GetLineItemsForSchoolLineItem,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolLineItem$outboundSchema.parse(
      getLineItemsForSchoolLineItem,
    ),
  );
}
export function getLineItemsForSchoolLineItemFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolLineItem' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolResponseBody$inboundSchema: z.ZodType<
  GetLineItemsForSchoolResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  lineItems: z.array(z.lazy(() => GetLineItemsForSchoolLineItem$inboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetLineItemsForSchoolResponseBody$Outbound = {
  lineItems: Array<GetLineItemsForSchoolLineItem$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetLineItemsForSchoolResponseBody$outboundSchema: z.ZodType<
  GetLineItemsForSchoolResponseBody$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolResponseBody
> = z.object({
  lineItems: z.array(
    z.lazy(() => GetLineItemsForSchoolLineItem$outboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getLineItemsForSchoolResponseBodyToJSON(
  getLineItemsForSchoolResponseBody: GetLineItemsForSchoolResponseBody,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolResponseBody$outboundSchema.parse(
      getLineItemsForSchoolResponseBody,
    ),
  );
}
export function getLineItemsForSchoolResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolResponseBody' from JSON`,
  );
}

/** @internal */
export const GetLineItemsForSchoolResponse$inboundSchema: z.ZodType<
  GetLineItemsForSchoolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetLineItemsForSchoolResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetLineItemsForSchoolResponse$Outbound = {
  Result: GetLineItemsForSchoolResponseBody$Outbound;
};

/** @internal */
export const GetLineItemsForSchoolResponse$outboundSchema: z.ZodType<
  GetLineItemsForSchoolResponse$Outbound,
  z.ZodTypeDef,
  GetLineItemsForSchoolResponse
> = z.object({
  result: z.lazy(() => GetLineItemsForSchoolResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getLineItemsForSchoolResponseToJSON(
  getLineItemsForSchoolResponse: GetLineItemsForSchoolResponse,
): string {
  return JSON.stringify(
    GetLineItemsForSchoolResponse$outboundSchema.parse(
      getLineItemsForSchoolResponse,
    ),
  );
}
export function getLineItemsForSchoolResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemsForSchoolResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemsForSchoolResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemsForSchoolResponse' from JSON`,
  );
}
