/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetResourcesForCourseOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetResourcesForCourseOrderBy = ClosedEnum<
  typeof GetResourcesForCourseOrderBy
>;

export type GetResourcesForCourseRequest = {
  /**
   * The sourcedId of the course
   */
  courseSourcedId: string;
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetResourcesForCourseOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetResourcesForCourseStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetResourcesForCourseStatus = ClosedEnum<
  typeof GetResourcesForCourseStatus
>;

export const GetResourcesForCourseRole = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
export type GetResourcesForCourseRole = ClosedEnum<
  typeof GetResourcesForCourseRole
>;

export const GetResourcesForCourseImportance = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
export type GetResourcesForCourseImportance = ClosedEnum<
  typeof GetResourcesForCourseImportance
>;

/**
 * Represents a digital resource of some kind.
 */
export type GetResourcesForCourseResource = {
  sourcedId: string;
  status: GetResourcesForCourseStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  roles?: Array<GetResourcesForCourseRole> | undefined;
  importance?: GetResourcesForCourseImportance | undefined;
  vendorResourceId: string;
  vendorId?: string | null | undefined;
  applicationId?: string | null | undefined;
};

/**
 * Successful response containing a collection of resources for the course
 */
export type GetResourcesForCourseResponseBody = {
  resources: Array<GetResourcesForCourseResource>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetResourcesForCourseResponse = {
  result: GetResourcesForCourseResponseBody;
};

/** @internal */
export const GetResourcesForCourseOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseOrderBy
> = z.nativeEnum(GetResourcesForCourseOrderBy);
/** @internal */
export const GetResourcesForCourseOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseOrderBy
> = GetResourcesForCourseOrderBy$inboundSchema;

/** @internal */
export const GetResourcesForCourseRequest$inboundSchema: z.ZodType<
  GetResourcesForCourseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  courseSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetResourcesForCourseOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetResourcesForCourseRequest$Outbound = {
  courseSourcedId: string;
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetResourcesForCourseRequest$outboundSchema: z.ZodType<
  GetResourcesForCourseRequest$Outbound,
  z.ZodTypeDef,
  GetResourcesForCourseRequest
> = z.object({
  courseSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetResourcesForCourseOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getResourcesForCourseRequestToJSON(
  getResourcesForCourseRequest: GetResourcesForCourseRequest,
): string {
  return JSON.stringify(
    GetResourcesForCourseRequest$outboundSchema.parse(
      getResourcesForCourseRequest,
    ),
  );
}
export function getResourcesForCourseRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForCourseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForCourseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForCourseRequest' from JSON`,
  );
}

/** @internal */
export const GetResourcesForCourseStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseStatus
> = z.nativeEnum(GetResourcesForCourseStatus);
/** @internal */
export const GetResourcesForCourseStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseStatus
> = GetResourcesForCourseStatus$inboundSchema;

/** @internal */
export const GetResourcesForCourseRole$inboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseRole
> = z.nativeEnum(GetResourcesForCourseRole);
/** @internal */
export const GetResourcesForCourseRole$outboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseRole
> = GetResourcesForCourseRole$inboundSchema;

/** @internal */
export const GetResourcesForCourseImportance$inboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseImportance
> = z.nativeEnum(GetResourcesForCourseImportance);
/** @internal */
export const GetResourcesForCourseImportance$outboundSchema: z.ZodNativeEnum<
  typeof GetResourcesForCourseImportance
> = GetResourcesForCourseImportance$inboundSchema;

/** @internal */
export const GetResourcesForCourseResource$inboundSchema: z.ZodType<
  GetResourcesForCourseResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetResourcesForCourseStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  roles: z.array(GetResourcesForCourseRole$inboundSchema).optional(),
  importance: GetResourcesForCourseImportance$inboundSchema.optional(),
  vendorResourceId: z.string(),
  vendorId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
});
/** @internal */
export type GetResourcesForCourseResource$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  title: string;
  roles?: Array<string> | undefined;
  importance?: string | undefined;
  vendorResourceId: string;
  vendorId?: string | null | undefined;
  applicationId?: string | null | undefined;
};

/** @internal */
export const GetResourcesForCourseResource$outboundSchema: z.ZodType<
  GetResourcesForCourseResource$Outbound,
  z.ZodTypeDef,
  GetResourcesForCourseResource
> = z.object({
  sourcedId: z.string(),
  status: GetResourcesForCourseStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  title: z.string(),
  roles: z.array(GetResourcesForCourseRole$outboundSchema).optional(),
  importance: GetResourcesForCourseImportance$outboundSchema.optional(),
  vendorResourceId: z.string(),
  vendorId: z.nullable(z.string()).optional(),
  applicationId: z.nullable(z.string()).optional(),
});

export function getResourcesForCourseResourceToJSON(
  getResourcesForCourseResource: GetResourcesForCourseResource,
): string {
  return JSON.stringify(
    GetResourcesForCourseResource$outboundSchema.parse(
      getResourcesForCourseResource,
    ),
  );
}
export function getResourcesForCourseResourceFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForCourseResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForCourseResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForCourseResource' from JSON`,
  );
}

/** @internal */
export const GetResourcesForCourseResponseBody$inboundSchema: z.ZodType<
  GetResourcesForCourseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  resources: z.array(z.lazy(() => GetResourcesForCourseResource$inboundSchema)),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetResourcesForCourseResponseBody$Outbound = {
  resources: Array<GetResourcesForCourseResource$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetResourcesForCourseResponseBody$outboundSchema: z.ZodType<
  GetResourcesForCourseResponseBody$Outbound,
  z.ZodTypeDef,
  GetResourcesForCourseResponseBody
> = z.object({
  resources: z.array(
    z.lazy(() => GetResourcesForCourseResource$outboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});

export function getResourcesForCourseResponseBodyToJSON(
  getResourcesForCourseResponseBody: GetResourcesForCourseResponseBody,
): string {
  return JSON.stringify(
    GetResourcesForCourseResponseBody$outboundSchema.parse(
      getResourcesForCourseResponseBody,
    ),
  );
}
export function getResourcesForCourseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForCourseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForCourseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForCourseResponseBody' from JSON`,
  );
}

/** @internal */
export const GetResourcesForCourseResponse$inboundSchema: z.ZodType<
  GetResourcesForCourseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetResourcesForCourseResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetResourcesForCourseResponse$Outbound = {
  Result: GetResourcesForCourseResponseBody$Outbound;
};

/** @internal */
export const GetResourcesForCourseResponse$outboundSchema: z.ZodType<
  GetResourcesForCourseResponse$Outbound,
  z.ZodTypeDef,
  GetResourcesForCourseResponse
> = z.object({
  result: z.lazy(() => GetResourcesForCourseResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getResourcesForCourseResponseToJSON(
  getResourcesForCourseResponse: GetResourcesForCourseResponse,
): string {
  return JSON.stringify(
    GetResourcesForCourseResponse$outboundSchema.parse(
      getResourcesForCourseResponse,
    ),
  );
}
export function getResourcesForCourseResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetResourcesForCourseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourcesForCourseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourcesForCourseResponse' from JSON`,
  );
}
