/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The order to sort the response by
 */
export const GetResultsForLineItemForClassOrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order to sort the response by
 */
export type GetResultsForLineItemForClassOrderBy = ClosedEnum<
  typeof GetResultsForLineItemForClassOrderBy
>;

export type GetResultsForLineItemForClassRequest = {
  /**
   * The sourcedId of the class
   */
  classSourcedId: string;
  /**
   * The sourcedId of the line item
   */
  lineItemSourcedId: string;
  /**
   * Comma-separated list of fields to include in the response
   */
  fields?: string | undefined;
  /**
   * The maximum number of items to return in the paginated response
   */
  limit?: number | undefined;
  /**
   * The number of items to skip in the paginated response
   */
  offset?: number | undefined;
  /**
   * The field to sort the response by
   */
  sort?: string | undefined;
  /**
   * The order to sort the response by
   */
  orderBy?: GetResultsForLineItemForClassOrderBy | undefined;
  /**
   * The filter to apply to the response
   */
  filter?: string | undefined;
  /**
   * The search query to apply to the response
   */
  search?: string | undefined;
};

export const GetResultsForLineItemForClassStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetResultsForLineItemForClassStatus = ClosedEnum<
  typeof GetResultsForLineItemForClassStatus
>;

export type GetResultsForLineItemForClassLineItem = {
  sourcedId: string;
};

export type GetResultsForLineItemForClassStudent = {
  sourcedId: string;
};

export type GetResultsForLineItemForClassClass = {
  sourcedId: string;
};

export type GetResultsForLineItemForClassScoreScale = {
  sourcedId: string;
};

export const GetResultsForLineItemForClassScoreStatus = {
  Exempt: "exempt",
  FullyGraded: "fully graded",
  NotSubmitted: "not submitted",
  PartiallyGraded: "partially graded",
  Submitted: "submitted",
} as const;
export type GetResultsForLineItemForClassScoreStatus = ClosedEnum<
  typeof GetResultsForLineItemForClassScoreStatus
>;

export type GetResultsForLineItemForClassLearningObjectiveResult = {
  learningObjectiveId: string;
  score?: number | undefined;
  textScore?: string | undefined;
};

export type GetResultsForLineItemForClassLearningObjectiveSet = {
  source: string;
  learningObjectiveResults: Array<
    GetResultsForLineItemForClassLearningObjectiveResult
  >;
};

/**
 * Represents a result.
 */
export type GetResultsForLineItemForClassResult = {
  sourcedId?: string | undefined;
  status: GetResultsForLineItemForClassStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  lineItem: GetResultsForLineItemForClassLineItem;
  student: GetResultsForLineItemForClassStudent;
  class?: GetResultsForLineItemForClassClass | null | undefined;
  scoreScale?: GetResultsForLineItemForClassScoreScale | null | undefined;
  scoreStatus: GetResultsForLineItemForClassScoreStatus;
  score?: number | null | undefined;
  textScore?: string | null | undefined;
  scoreDate: Date;
  comment?: string | null | undefined;
  learningObjectiveSet?:
    | Array<GetResultsForLineItemForClassLearningObjectiveSet>
    | null
    | undefined;
  inProgress?: string | undefined;
  incomplete?: string | undefined;
  late?: string | undefined;
  missing?: string | undefined;
};

/**
 * Successful response containing a collection of results for the specified line item in the class
 */
export type GetResultsForLineItemForClassResponseBody = {
  results: Array<GetResultsForLineItemForClassResult>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

export type GetResultsForLineItemForClassResponse = {
  result: GetResultsForLineItemForClassResponseBody;
};

/** @internal */
export const GetResultsForLineItemForClassOrderBy$inboundSchema:
  z.ZodNativeEnum<typeof GetResultsForLineItemForClassOrderBy> = z.nativeEnum(
    GetResultsForLineItemForClassOrderBy,
  );
/** @internal */
export const GetResultsForLineItemForClassOrderBy$outboundSchema:
  z.ZodNativeEnum<typeof GetResultsForLineItemForClassOrderBy> =
    GetResultsForLineItemForClassOrderBy$inboundSchema;

/** @internal */
export const GetResultsForLineItemForClassRequest$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  classSourcedId: z.string(),
  lineItemSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetResultsForLineItemForClassOrderBy$inboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});
/** @internal */
export type GetResultsForLineItemForClassRequest$Outbound = {
  classSourcedId: string;
  lineItemSourcedId: string;
  fields?: string | undefined;
  limit: number;
  offset: number;
  sort?: string | undefined;
  orderBy?: string | undefined;
  filter?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetResultsForLineItemForClassRequest$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassRequest$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassRequest
> = z.object({
  classSourcedId: z.string(),
  lineItemSourcedId: z.string(),
  fields: z.string().optional(),
  limit: z.number().int().default(100),
  offset: z.number().int().default(0),
  sort: z.string().optional(),
  orderBy: GetResultsForLineItemForClassOrderBy$outboundSchema.optional(),
  filter: z.string().optional(),
  search: z.string().optional(),
});

export function getResultsForLineItemForClassRequestToJSON(
  getResultsForLineItemForClassRequest: GetResultsForLineItemForClassRequest,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassRequest$outboundSchema.parse(
      getResultsForLineItemForClassRequest,
    ),
  );
}
export function getResultsForLineItemForClassRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassRequest' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetResultsForLineItemForClassStatus
> = z.nativeEnum(GetResultsForLineItemForClassStatus);
/** @internal */
export const GetResultsForLineItemForClassStatus$outboundSchema:
  z.ZodNativeEnum<typeof GetResultsForLineItemForClassStatus> =
    GetResultsForLineItemForClassStatus$inboundSchema;

/** @internal */
export const GetResultsForLineItemForClassLineItem$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetResultsForLineItemForClassLineItem$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetResultsForLineItemForClassLineItem$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassLineItem$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassLineItem
> = z.object({
  sourcedId: z.string(),
});

export function getResultsForLineItemForClassLineItemToJSON(
  getResultsForLineItemForClassLineItem: GetResultsForLineItemForClassLineItem,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassLineItem$outboundSchema.parse(
      getResultsForLineItemForClassLineItem,
    ),
  );
}
export function getResultsForLineItemForClassLineItemFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassLineItem' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassStudent$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassStudent,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetResultsForLineItemForClassStudent$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetResultsForLineItemForClassStudent$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassStudent$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassStudent
> = z.object({
  sourcedId: z.string(),
});

export function getResultsForLineItemForClassStudentToJSON(
  getResultsForLineItemForClassStudent: GetResultsForLineItemForClassStudent,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassStudent$outboundSchema.parse(
      getResultsForLineItemForClassStudent,
    ),
  );
}
export function getResultsForLineItemForClassStudentFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassStudent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassStudent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassStudent' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassClass$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassClass,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetResultsForLineItemForClassClass$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetResultsForLineItemForClassClass$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassClass$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassClass
> = z.object({
  sourcedId: z.string(),
});

export function getResultsForLineItemForClassClassToJSON(
  getResultsForLineItemForClassClass: GetResultsForLineItemForClassClass,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassClass$outboundSchema.parse(
      getResultsForLineItemForClassClass,
    ),
  );
}
export function getResultsForLineItemForClassClassFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassClass, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassClass$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassClass' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassScoreScale$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassScoreScale,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetResultsForLineItemForClassScoreScale$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetResultsForLineItemForClassScoreScale$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassScoreScale$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassScoreScale
> = z.object({
  sourcedId: z.string(),
});

export function getResultsForLineItemForClassScoreScaleToJSON(
  getResultsForLineItemForClassScoreScale:
    GetResultsForLineItemForClassScoreScale,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassScoreScale$outboundSchema.parse(
      getResultsForLineItemForClassScoreScale,
    ),
  );
}
export function getResultsForLineItemForClassScoreScaleFromJSON(
  jsonString: string,
): SafeParseResult<
  GetResultsForLineItemForClassScoreScale,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassScoreScale$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetResultsForLineItemForClassScoreScale' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassScoreStatus$inboundSchema:
  z.ZodNativeEnum<typeof GetResultsForLineItemForClassScoreStatus> = z
    .nativeEnum(GetResultsForLineItemForClassScoreStatus);
/** @internal */
export const GetResultsForLineItemForClassScoreStatus$outboundSchema:
  z.ZodNativeEnum<typeof GetResultsForLineItemForClassScoreStatus> =
    GetResultsForLineItemForClassScoreStatus$inboundSchema;

/** @internal */
export const GetResultsForLineItemForClassLearningObjectiveResult$inboundSchema:
  z.ZodType<
    GetResultsForLineItemForClassLearningObjectiveResult,
    z.ZodTypeDef,
    unknown
  > = z.object({
    learningObjectiveId: z.string(),
    score: z.number().optional(),
    textScore: z.string().optional(),
  });
/** @internal */
export type GetResultsForLineItemForClassLearningObjectiveResult$Outbound = {
  learningObjectiveId: string;
  score?: number | undefined;
  textScore?: string | undefined;
};

/** @internal */
export const GetResultsForLineItemForClassLearningObjectiveResult$outboundSchema:
  z.ZodType<
    GetResultsForLineItemForClassLearningObjectiveResult$Outbound,
    z.ZodTypeDef,
    GetResultsForLineItemForClassLearningObjectiveResult
  > = z.object({
    learningObjectiveId: z.string(),
    score: z.number().optional(),
    textScore: z.string().optional(),
  });

export function getResultsForLineItemForClassLearningObjectiveResultToJSON(
  getResultsForLineItemForClassLearningObjectiveResult:
    GetResultsForLineItemForClassLearningObjectiveResult,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassLearningObjectiveResult$outboundSchema.parse(
      getResultsForLineItemForClassLearningObjectiveResult,
    ),
  );
}
export function getResultsForLineItemForClassLearningObjectiveResultFromJSON(
  jsonString: string,
): SafeParseResult<
  GetResultsForLineItemForClassLearningObjectiveResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassLearningObjectiveResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetResultsForLineItemForClassLearningObjectiveResult' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassLearningObjectiveSet$inboundSchema:
  z.ZodType<
    GetResultsForLineItemForClassLearningObjectiveSet,
    z.ZodTypeDef,
    unknown
  > = z.object({
    source: z.string(),
    learningObjectiveResults: z.array(
      z.lazy(() =>
        GetResultsForLineItemForClassLearningObjectiveResult$inboundSchema
      ),
    ),
  });
/** @internal */
export type GetResultsForLineItemForClassLearningObjectiveSet$Outbound = {
  source: string;
  learningObjectiveResults: Array<
    GetResultsForLineItemForClassLearningObjectiveResult$Outbound
  >;
};

/** @internal */
export const GetResultsForLineItemForClassLearningObjectiveSet$outboundSchema:
  z.ZodType<
    GetResultsForLineItemForClassLearningObjectiveSet$Outbound,
    z.ZodTypeDef,
    GetResultsForLineItemForClassLearningObjectiveSet
  > = z.object({
    source: z.string(),
    learningObjectiveResults: z.array(
      z.lazy(() =>
        GetResultsForLineItemForClassLearningObjectiveResult$outboundSchema
      ),
    ),
  });

export function getResultsForLineItemForClassLearningObjectiveSetToJSON(
  getResultsForLineItemForClassLearningObjectiveSet:
    GetResultsForLineItemForClassLearningObjectiveSet,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassLearningObjectiveSet$outboundSchema.parse(
      getResultsForLineItemForClassLearningObjectiveSet,
    ),
  );
}
export function getResultsForLineItemForClassLearningObjectiveSetFromJSON(
  jsonString: string,
): SafeParseResult<
  GetResultsForLineItemForClassLearningObjectiveSet,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassLearningObjectiveSet$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetResultsForLineItemForClassLearningObjectiveSet' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassResult$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string().optional(),
  status: GetResultsForLineItemForClassStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  lineItem: z.lazy(() => GetResultsForLineItemForClassLineItem$inboundSchema),
  student: z.lazy(() => GetResultsForLineItemForClassStudent$inboundSchema),
  class: z.nullable(
    z.lazy(() => GetResultsForLineItemForClassClass$inboundSchema),
  ).optional(),
  scoreScale: z.nullable(
    z.lazy(() => GetResultsForLineItemForClassScoreScale$inboundSchema),
  ).optional(),
  scoreStatus: GetResultsForLineItemForClassScoreStatus$inboundSchema,
  score: z.nullable(z.number()).optional(),
  textScore: z.nullable(z.string()).optional(),
  scoreDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  comment: z.nullable(z.string()).optional(),
  learningObjectiveSet: z.nullable(
    z.array(z.lazy(() =>
      GetResultsForLineItemForClassLearningObjectiveSet$inboundSchema
    )),
  ).optional(),
  inProgress: z.string().optional(),
  incomplete: z.string().optional(),
  late: z.string().optional(),
  missing: z.string().optional(),
});
/** @internal */
export type GetResultsForLineItemForClassResult$Outbound = {
  sourcedId?: string | undefined;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  lineItem: GetResultsForLineItemForClassLineItem$Outbound;
  student: GetResultsForLineItemForClassStudent$Outbound;
  class?: GetResultsForLineItemForClassClass$Outbound | null | undefined;
  scoreScale?:
    | GetResultsForLineItemForClassScoreScale$Outbound
    | null
    | undefined;
  scoreStatus: string;
  score?: number | null | undefined;
  textScore?: string | null | undefined;
  scoreDate: string;
  comment?: string | null | undefined;
  learningObjectiveSet?:
    | Array<GetResultsForLineItemForClassLearningObjectiveSet$Outbound>
    | null
    | undefined;
  inProgress?: string | undefined;
  incomplete?: string | undefined;
  late?: string | undefined;
  missing?: string | undefined;
};

/** @internal */
export const GetResultsForLineItemForClassResult$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassResult$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassResult
> = z.object({
  sourcedId: z.string().optional(),
  status: GetResultsForLineItemForClassStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  lineItem: z.lazy(() => GetResultsForLineItemForClassLineItem$outboundSchema),
  student: z.lazy(() => GetResultsForLineItemForClassStudent$outboundSchema),
  class: z.nullable(
    z.lazy(() => GetResultsForLineItemForClassClass$outboundSchema),
  ).optional(),
  scoreScale: z.nullable(
    z.lazy(() => GetResultsForLineItemForClassScoreScale$outboundSchema),
  ).optional(),
  scoreStatus: GetResultsForLineItemForClassScoreStatus$outboundSchema,
  score: z.nullable(z.number()).optional(),
  textScore: z.nullable(z.string()).optional(),
  scoreDate: z.date().transform(v => v.toISOString()),
  comment: z.nullable(z.string()).optional(),
  learningObjectiveSet: z.nullable(
    z.array(z.lazy(() =>
      GetResultsForLineItemForClassLearningObjectiveSet$outboundSchema
    )),
  ).optional(),
  inProgress: z.string().optional(),
  incomplete: z.string().optional(),
  late: z.string().optional(),
  missing: z.string().optional(),
});

export function getResultsForLineItemForClassResultToJSON(
  getResultsForLineItemForClassResult: GetResultsForLineItemForClassResult,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassResult$outboundSchema.parse(
      getResultsForLineItemForClassResult,
    ),
  );
}
export function getResultsForLineItemForClassResultFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassResult' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassResponseBody$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(
    z.lazy(() => GetResultsForLineItemForClassResult$inboundSchema),
  ),
  totalCount: z.number(),
  pageCount: z.number(),
  pageNumber: z.number(),
  offset: z.number(),
  limit: z.number(),
});
/** @internal */
export type GetResultsForLineItemForClassResponseBody$Outbound = {
  results: Array<GetResultsForLineItemForClassResult$Outbound>;
  totalCount: number;
  pageCount: number;
  pageNumber: number;
  offset: number;
  limit: number;
};

/** @internal */
export const GetResultsForLineItemForClassResponseBody$outboundSchema:
  z.ZodType<
    GetResultsForLineItemForClassResponseBody$Outbound,
    z.ZodTypeDef,
    GetResultsForLineItemForClassResponseBody
  > = z.object({
    results: z.array(
      z.lazy(() => GetResultsForLineItemForClassResult$outboundSchema),
    ),
    totalCount: z.number(),
    pageCount: z.number(),
    pageNumber: z.number(),
    offset: z.number(),
    limit: z.number(),
  });

export function getResultsForLineItemForClassResponseBodyToJSON(
  getResultsForLineItemForClassResponseBody:
    GetResultsForLineItemForClassResponseBody,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassResponseBody$outboundSchema.parse(
      getResultsForLineItemForClassResponseBody,
    ),
  );
}
export function getResultsForLineItemForClassResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetResultsForLineItemForClassResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetResultsForLineItemForClassResponseBody' from JSON`,
  );
}

/** @internal */
export const GetResultsForLineItemForClassResponse$inboundSchema: z.ZodType<
  GetResultsForLineItemForClassResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetResultsForLineItemForClassResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetResultsForLineItemForClassResponse$Outbound = {
  Result: GetResultsForLineItemForClassResponseBody$Outbound;
};

/** @internal */
export const GetResultsForLineItemForClassResponse$outboundSchema: z.ZodType<
  GetResultsForLineItemForClassResponse$Outbound,
  z.ZodTypeDef,
  GetResultsForLineItemForClassResponse
> = z.object({
  result: z.lazy(() =>
    GetResultsForLineItemForClassResponseBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getResultsForLineItemForClassResponseToJSON(
  getResultsForLineItemForClassResponse: GetResultsForLineItemForClassResponse,
): string {
  return JSON.stringify(
    GetResultsForLineItemForClassResponse$outboundSchema.parse(
      getResultsForLineItemForClassResponse,
    ),
  );
}
export function getResultsForLineItemForClassResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetResultsForLineItemForClassResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetResultsForLineItemForClassResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResultsForLineItemForClassResponse' from JSON`,
  );
}
