/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserWithDemographicsRequest = {
  /**
   * The sourcedId of the user
   */
  sourcedId: string;
};

export const GetUserWithDemographicsStatus = {
  Active: "active",
  Tobedeleted: "tobedeleted",
} as const;
export type GetUserWithDemographicsStatus = ClosedEnum<
  typeof GetUserWithDemographicsStatus
>;

export type GetUserWithDemographicsUserId = {
  type: string;
  identifier: string;
};

export const GetUserWithDemographicsRoleType = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
export type GetUserWithDemographicsRoleType = ClosedEnum<
  typeof GetUserWithDemographicsRoleType
>;

export const GetUserWithDemographicsRoleEnum = {
  Administrator: "administrator",
  Aide: "aide",
  Guardian: "guardian",
  Parent: "parent",
  Proctor: "proctor",
  Relative: "relative",
  Student: "student",
  Teacher: "teacher",
} as const;
export type GetUserWithDemographicsRoleEnum = ClosedEnum<
  typeof GetUserWithDemographicsRoleEnum
>;

export type GetUserWithDemographicsOrg = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetUserWithDemographicsRole = {
  roleType: GetUserWithDemographicsRoleType;
  role: GetUserWithDemographicsRoleEnum;
  org: GetUserWithDemographicsOrg;
  userProfile?: string | undefined;
  beginDate: string | null;
  endDate: string | null;
};

export const GetUserWithDemographicsType = {
  AcademicSession: "academicSession",
  AssessmentLineItem: "assessmentLineItem",
  Category: "category",
  Class: "class",
  Course: "course",
  Demographics: "demographics",
  Enrollment: "enrollment",
  GradingPeriod: "gradingPeriod",
  LineItem: "lineItem",
  Org: "org",
  Resource: "resource",
  Result: "result",
  ScoreScale: "scoreScale",
  Student: "student",
  Teacher: "teacher",
  Term: "term",
  User: "user",
  ComponentResource: "componentResource",
  CourseComponent: "courseComponent",
} as const;
export type GetUserWithDemographicsType = ClosedEnum<
  typeof GetUserWithDemographicsType
>;

export type GetUserWithDemographicsAgent = {
  href: string;
  sourcedId: string;
  type: GetUserWithDemographicsType;
};

export type GetUserWithDemographicsPrimaryOrg = {
  href: string;
  sourcedId: string;
  type: string;
};

export type GetUserWithDemographicsUser = {
  sourcedId: string;
  status: GetUserWithDemographicsStatus;
  dateLastModified?: Date | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  userMasterIdentifier?: string | null | undefined;
  username?: string | null | undefined;
  userIds?: Array<GetUserWithDemographicsUserId> | undefined;
  enabledUser: boolean;
  givenName: string;
  familyName: string;
  middleName?: string | null | undefined;
  roles: Array<GetUserWithDemographicsRole>;
  agents: Array<GetUserWithDemographicsAgent>;
  primaryOrg?: GetUserWithDemographicsPrimaryOrg | undefined;
  email?: string | null | undefined;
  preferredFirstName?: string | null | undefined;
  preferredMiddleName?: string | null | undefined;
  preferredLastName?: string | null | undefined;
  pronouns?: string | null | undefined;
  grades?: Array<string> | undefined;
  password?: string | null | undefined;
  sms?: string | null | undefined;
  phone?: string | null | undefined;
  demographics?: components.Demographics | null | undefined;
};

/**
 * Successful response with the user with demographics
 */
export type GetUserWithDemographicsResponse = {
  user: GetUserWithDemographicsUser;
};

/** @internal */
export const GetUserWithDemographicsRequest$inboundSchema: z.ZodType<
  GetUserWithDemographicsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
});
/** @internal */
export type GetUserWithDemographicsRequest$Outbound = {
  sourcedId: string;
};

/** @internal */
export const GetUserWithDemographicsRequest$outboundSchema: z.ZodType<
  GetUserWithDemographicsRequest$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsRequest
> = z.object({
  sourcedId: z.string(),
});

export function getUserWithDemographicsRequestToJSON(
  getUserWithDemographicsRequest: GetUserWithDemographicsRequest,
): string {
  return JSON.stringify(
    GetUserWithDemographicsRequest$outboundSchema.parse(
      getUserWithDemographicsRequest,
    ),
  );
}
export function getUserWithDemographicsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsRequest' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsStatus
> = z.nativeEnum(GetUserWithDemographicsStatus);
/** @internal */
export const GetUserWithDemographicsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsStatus
> = GetUserWithDemographicsStatus$inboundSchema;

/** @internal */
export const GetUserWithDemographicsUserId$inboundSchema: z.ZodType<
  GetUserWithDemographicsUserId,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  identifier: z.string(),
});
/** @internal */
export type GetUserWithDemographicsUserId$Outbound = {
  type: string;
  identifier: string;
};

/** @internal */
export const GetUserWithDemographicsUserId$outboundSchema: z.ZodType<
  GetUserWithDemographicsUserId$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsUserId
> = z.object({
  type: z.string(),
  identifier: z.string(),
});

export function getUserWithDemographicsUserIdToJSON(
  getUserWithDemographicsUserId: GetUserWithDemographicsUserId,
): string {
  return JSON.stringify(
    GetUserWithDemographicsUserId$outboundSchema.parse(
      getUserWithDemographicsUserId,
    ),
  );
}
export function getUserWithDemographicsUserIdFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsUserId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsUserId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsUserId' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsRoleType$inboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsRoleType
> = z.nativeEnum(GetUserWithDemographicsRoleType);
/** @internal */
export const GetUserWithDemographicsRoleType$outboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsRoleType
> = GetUserWithDemographicsRoleType$inboundSchema;

/** @internal */
export const GetUserWithDemographicsRoleEnum$inboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsRoleEnum
> = z.nativeEnum(GetUserWithDemographicsRoleEnum);
/** @internal */
export const GetUserWithDemographicsRoleEnum$outboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsRoleEnum
> = GetUserWithDemographicsRoleEnum$inboundSchema;

/** @internal */
export const GetUserWithDemographicsOrg$inboundSchema: z.ZodType<
  GetUserWithDemographicsOrg,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetUserWithDemographicsOrg$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetUserWithDemographicsOrg$outboundSchema: z.ZodType<
  GetUserWithDemographicsOrg$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsOrg
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getUserWithDemographicsOrgToJSON(
  getUserWithDemographicsOrg: GetUserWithDemographicsOrg,
): string {
  return JSON.stringify(
    GetUserWithDemographicsOrg$outboundSchema.parse(getUserWithDemographicsOrg),
  );
}
export function getUserWithDemographicsOrgFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsOrg, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsOrg$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsOrg' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsRole$inboundSchema: z.ZodType<
  GetUserWithDemographicsRole,
  z.ZodTypeDef,
  unknown
> = z.object({
  roleType: GetUserWithDemographicsRoleType$inboundSchema,
  role: GetUserWithDemographicsRoleEnum$inboundSchema,
  org: z.lazy(() => GetUserWithDemographicsOrg$inboundSchema),
  userProfile: z.string().optional(),
  beginDate: z.nullable(z.string()),
  endDate: z.nullable(z.string()),
});
/** @internal */
export type GetUserWithDemographicsRole$Outbound = {
  roleType: string;
  role: string;
  org: GetUserWithDemographicsOrg$Outbound;
  userProfile?: string | undefined;
  beginDate: string | null;
  endDate: string | null;
};

/** @internal */
export const GetUserWithDemographicsRole$outboundSchema: z.ZodType<
  GetUserWithDemographicsRole$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsRole
> = z.object({
  roleType: GetUserWithDemographicsRoleType$outboundSchema,
  role: GetUserWithDemographicsRoleEnum$outboundSchema,
  org: z.lazy(() => GetUserWithDemographicsOrg$outboundSchema),
  userProfile: z.string().optional(),
  beginDate: z.nullable(z.string()),
  endDate: z.nullable(z.string()),
});

export function getUserWithDemographicsRoleToJSON(
  getUserWithDemographicsRole: GetUserWithDemographicsRole,
): string {
  return JSON.stringify(
    GetUserWithDemographicsRole$outboundSchema.parse(
      getUserWithDemographicsRole,
    ),
  );
}
export function getUserWithDemographicsRoleFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsRole' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsType$inboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsType
> = z.nativeEnum(GetUserWithDemographicsType);
/** @internal */
export const GetUserWithDemographicsType$outboundSchema: z.ZodNativeEnum<
  typeof GetUserWithDemographicsType
> = GetUserWithDemographicsType$inboundSchema;

/** @internal */
export const GetUserWithDemographicsAgent$inboundSchema: z.ZodType<
  GetUserWithDemographicsAgent,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: GetUserWithDemographicsType$inboundSchema,
});
/** @internal */
export type GetUserWithDemographicsAgent$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetUserWithDemographicsAgent$outboundSchema: z.ZodType<
  GetUserWithDemographicsAgent$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsAgent
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: GetUserWithDemographicsType$outboundSchema,
});

export function getUserWithDemographicsAgentToJSON(
  getUserWithDemographicsAgent: GetUserWithDemographicsAgent,
): string {
  return JSON.stringify(
    GetUserWithDemographicsAgent$outboundSchema.parse(
      getUserWithDemographicsAgent,
    ),
  );
}
export function getUserWithDemographicsAgentFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsAgent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsAgent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsAgent' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsPrimaryOrg$inboundSchema: z.ZodType<
  GetUserWithDemographicsPrimaryOrg,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});
/** @internal */
export type GetUserWithDemographicsPrimaryOrg$Outbound = {
  href: string;
  sourcedId: string;
  type: string;
};

/** @internal */
export const GetUserWithDemographicsPrimaryOrg$outboundSchema: z.ZodType<
  GetUserWithDemographicsPrimaryOrg$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsPrimaryOrg
> = z.object({
  href: z.string(),
  sourcedId: z.string(),
  type: z.string(),
});

export function getUserWithDemographicsPrimaryOrgToJSON(
  getUserWithDemographicsPrimaryOrg: GetUserWithDemographicsPrimaryOrg,
): string {
  return JSON.stringify(
    GetUserWithDemographicsPrimaryOrg$outboundSchema.parse(
      getUserWithDemographicsPrimaryOrg,
    ),
  );
}
export function getUserWithDemographicsPrimaryOrgFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsPrimaryOrg, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsPrimaryOrg$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsPrimaryOrg' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsUser$inboundSchema: z.ZodType<
  GetUserWithDemographicsUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  sourcedId: z.string(),
  status: GetUserWithDemographicsStatus$inboundSchema,
  dateLastModified: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  userMasterIdentifier: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
  userIds: z.array(z.lazy(() => GetUserWithDemographicsUserId$inboundSchema))
    .optional(),
  enabledUser: z.boolean(),
  givenName: z.string(),
  familyName: z.string(),
  middleName: z.nullable(z.string()).optional(),
  roles: z.array(z.lazy(() => GetUserWithDemographicsRole$inboundSchema)),
  agents: z.array(z.lazy(() => GetUserWithDemographicsAgent$inboundSchema)),
  primaryOrg: z.lazy(() => GetUserWithDemographicsPrimaryOrg$inboundSchema)
    .optional(),
  email: z.nullable(z.string()).optional(),
  preferredFirstName: z.nullable(z.string()).optional(),
  preferredMiddleName: z.nullable(z.string()).optional(),
  preferredLastName: z.nullable(z.string()).optional(),
  pronouns: z.nullable(z.string()).optional(),
  grades: z.array(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  sms: z.nullable(z.string()).optional(),
  phone: z.nullable(z.string()).optional(),
  demographics: z.nullable(components.Demographics$inboundSchema).optional(),
});
/** @internal */
export type GetUserWithDemographicsUser$Outbound = {
  sourcedId: string;
  status: string;
  dateLastModified?: string | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  userMasterIdentifier?: string | null | undefined;
  username?: string | null | undefined;
  userIds?: Array<GetUserWithDemographicsUserId$Outbound> | undefined;
  enabledUser: boolean;
  givenName: string;
  familyName: string;
  middleName?: string | null | undefined;
  roles: Array<GetUserWithDemographicsRole$Outbound>;
  agents: Array<GetUserWithDemographicsAgent$Outbound>;
  primaryOrg?: GetUserWithDemographicsPrimaryOrg$Outbound | undefined;
  email?: string | null | undefined;
  preferredFirstName?: string | null | undefined;
  preferredMiddleName?: string | null | undefined;
  preferredLastName?: string | null | undefined;
  pronouns?: string | null | undefined;
  grades?: Array<string> | undefined;
  password?: string | null | undefined;
  sms?: string | null | undefined;
  phone?: string | null | undefined;
  demographics?: components.Demographics$Outbound | null | undefined;
};

/** @internal */
export const GetUserWithDemographicsUser$outboundSchema: z.ZodType<
  GetUserWithDemographicsUser$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsUser
> = z.object({
  sourcedId: z.string(),
  status: GetUserWithDemographicsStatus$outboundSchema,
  dateLastModified: z.date().transform(v => v.toISOString()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  userMasterIdentifier: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
  userIds: z.array(z.lazy(() => GetUserWithDemographicsUserId$outboundSchema))
    .optional(),
  enabledUser: z.boolean(),
  givenName: z.string(),
  familyName: z.string(),
  middleName: z.nullable(z.string()).optional(),
  roles: z.array(z.lazy(() => GetUserWithDemographicsRole$outboundSchema)),
  agents: z.array(z.lazy(() => GetUserWithDemographicsAgent$outboundSchema)),
  primaryOrg: z.lazy(() => GetUserWithDemographicsPrimaryOrg$outboundSchema)
    .optional(),
  email: z.nullable(z.string()).optional(),
  preferredFirstName: z.nullable(z.string()).optional(),
  preferredMiddleName: z.nullable(z.string()).optional(),
  preferredLastName: z.nullable(z.string()).optional(),
  pronouns: z.nullable(z.string()).optional(),
  grades: z.array(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  sms: z.nullable(z.string()).optional(),
  phone: z.nullable(z.string()).optional(),
  demographics: z.nullable(components.Demographics$outboundSchema).optional(),
});

export function getUserWithDemographicsUserToJSON(
  getUserWithDemographicsUser: GetUserWithDemographicsUser,
): string {
  return JSON.stringify(
    GetUserWithDemographicsUser$outboundSchema.parse(
      getUserWithDemographicsUser,
    ),
  );
}
export function getUserWithDemographicsUserFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsUser' from JSON`,
  );
}

/** @internal */
export const GetUserWithDemographicsResponse$inboundSchema: z.ZodType<
  GetUserWithDemographicsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  user: z.lazy(() => GetUserWithDemographicsUser$inboundSchema),
});
/** @internal */
export type GetUserWithDemographicsResponse$Outbound = {
  user: GetUserWithDemographicsUser$Outbound;
};

/** @internal */
export const GetUserWithDemographicsResponse$outboundSchema: z.ZodType<
  GetUserWithDemographicsResponse$Outbound,
  z.ZodTypeDef,
  GetUserWithDemographicsResponse
> = z.object({
  user: z.lazy(() => GetUserWithDemographicsUser$outboundSchema),
});

export function getUserWithDemographicsResponseToJSON(
  getUserWithDemographicsResponse: GetUserWithDemographicsResponse,
): string {
  return JSON.stringify(
    GetUserWithDemographicsResponse$outboundSchema.parse(
      getUserWithDemographicsResponse,
    ),
  );
}
export function getUserWithDemographicsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserWithDemographicsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserWithDemographicsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserWithDemographicsResponse' from JSON`,
  );
}
